# GitHub Issues

Машиночитаемый источник задач. `scripts/create-issues.sh` парсит этот файл и создаёт
метки, вехи и issues через `gh`. Формат менять осторожно — парсер завязан на маркеры.

Метки: `architecture` `dsp` `midi` `ui` `build` `ci` `test` `docs` `perf` `daw-compat`
`research` `release` `post-mvp`

---

## [1] Инициализировать репозиторий и структуру проекта
**Labels:** build, architecture
**Milestone:** M0

### Описание
Git-репозиторий, .gitignore под C++/JUCE/macOS/CMake, лицензия, базовый README.
Структура каталогов: `Source/`, `Source/DSP/`, `Source/UI/`, `docs/`, `scripts/`, `tests/`.
JUCE подключить как git submodule в `libs/JUCE` (фиксированный тег, не master).

### Критерии приёмки
- [ ] `git clone --recursive` даёт полностью рабочее дерево
- [ ] `.gitignore` исключает `build/`, `.DS_Store`, `*.vst3`, `*.component`, артефакты IDE
- [ ] JUCE зафиксирован на конкретном теге, версия записана в README
- [ ] В репозитории нет бинарников и папок сборки

---

## [2] CMake + JUCE: таргеты VST3, AU, Standalone
**Labels:** build
**Milestone:** M0

### Описание
`CMakeLists.txt` с `juce_add_plugin`. Имя продукта, код плагина, вендор.
Обязательно `NEEDS_MIDI_INPUT TRUE` — без него FL Studio не покажет MIDI-вход.
`IS_SYNTH FALSE`, категория эффекта. C++20. На macOS — universal binary (arm64 + x86_64).
Учесть: на машине разработки стоит только Command Line Tools, полного Xcode нет — проверить,
собирается ли AU-таргет без него, и записать вывод в README.

### Критерии приёмки
- [ ] `cmake -B build && cmake --build build` собирает VST3, AU и Standalone
- [ ] Standalone запускается и пропускает аудио насквозь
- [ ] VST3 виден в FL Studio, AU — в Logic/GarageBand
- [ ] У плагина есть MIDI-вход в списке DAW
- [ ] Требование Xcode для AU выяснено и задокументировано

---

## [3] CI: сборка на macOS и Windows
**Labels:** build, ci
**Milestone:** M0

### Описание
GitHub Actions: матрица macos-latest + windows-latest, кэш зависимостей,
сборка Release, загрузка артефактов сборки.

### Критерии приёмки
- [ ] Workflow запускается на push и pull request
- [ ] Обе платформы собираются зелёными
- [ ] Артефакты (.vst3, .component) доступны для скачивания из прогона
- [ ] Красная сборка блокирует merge

---

## [4] pluginval в CI, strictness 10
**Labels:** test, ci
**Milestone:** M0

### Описание
Скачивать pluginval в CI и прогонять на собранных VST3/AU со strictness level 10.
Это ловит большинство нарушений контракта хоста до того, как их поймает FL Studio.

### Критерии приёмки
- [ ] pluginval проходит на strictness 10 для VST3 и AU
- [ ] Падение валидации роняет сборку
- [ ] Лог валидации сохраняется как артефакт

---

## [5] ADR: архитектура ядра — voice-based tap delay
**Labels:** architecture, research
**Milestone:** M0

### Описание
Зафиксировать решение из `docs/ANALYSIS.md` §3 как ADR в `docs/adr/0001-voice-based-core.md`.
Общий кольцевой буфер записи, MIDI-нота порождает независимый голос со своей позицией чтения,
ratio, огибающей и паном. Явно записать, почему отвергнут feedback-delay-с-питчем-в-петле.
Набросать интерфейсы: `DelayBuffer`, `Voice`, `VoiceManager`, `PitchShifter`.

### Критерии приёмки
- [ ] ADR написан, решение и альтернативы зафиксированы
- [ ] Описаны заголовочные интерфейсы четырёх классов
- [ ] Явно сказано, как голос получает и отдаёт сэмплы (pull или push)
- [ ] Указан лимит полифонии и стратегия voice stealing

---

## [6] ADR: алгоритм pitch shift и лицензии библиотек
**Labels:** dsp, research
**Milestone:** M0

### Описание
Зафиксировать: MVP на собственном dual-head varispeed питчере. Проверить и записать
лицензии кандидатов на HQ-режим — Signalsmith Stretch и Rubber Band Library
(Rubber Band требует платной лицензии для закрытого коммерческого продукта — проверить актуальные условия).
Заложить абстракцию `PitchShifter` так, чтобы второй движок подключался за флагом качества.

### Критерии приёмки
- [ ] ADR `docs/adr/0002-pitch-engine.md` написан
- [ ] Лицензии кандидатов проверены по первоисточникам и записаны с датой проверки
- [ ] Интерфейс `PitchShifter` допускает вторую реализацию без переписывания вызывающего кода
- [ ] Записано, какая внутренняя латентность у каждого варианта

---

## [7] Кольцевой буфер задержки
**Labels:** dsp
**Milestone:** M1

### Описание
`DelayBuffer`: запись потоком, чтение по дробному смещению назад. Размер под максимальный
delay time плюс запас на алгоритмическую латентность питчера и на длину ноты.
Многоканальность. Realtime-safe: аллокация только в `prepareToPlay`.

### Критерии приёмки
- [ ] Запись и чтение корректны на границе кольца (тест на wrap-around)
- [ ] Чтение по дробному смещению не выходит за пределы буфера
- [ ] Ноль аллокаций в `processBlock` (проверено вручную или санитайзером)
- [ ] Есть офлайн-тест: импульс на входе появляется на выходе ровно через N сэмплов

---

## [8] Интерполяция дробного чтения
**Labels:** dsp
**Milestone:** M1

### Описание
Catmull-Rom или Lagrange 3-го порядка для чтения по дробной позиции. Линейной интерполяции
недостаточно: при варьирующейся скорости чтения (а именно так работает питчер) она даёт
слышимое затухание верха и модуляционные искажения.

### Критерии приёмки
- [ ] Реализована интерполяция минимум 3-го порядка
- [ ] Свип-тест: развёртка синуса читается без слышимых артефактов
- [ ] Замерено и записано, насколько лучше линейной по THD на статичном сдвиге

---

## [9] Каркас AudioProcessor и раскладка шин
**Labels:** architecture
**Milestone:** M1

### Описание
`isBusesLayoutSupported`: моно→моно, стерео→стерео, и моно→стерео (вокал моно, подклад широкий).
`prepareToPlay` выделяет всё заранее, `releaseResources` чистит. `ScopedNoDenormals`.
Корректная реакция на смену sample rate и размера блока на лету.

### Критерии приёмки
- [ ] Поддержаны раскладки mono→mono, stereo→stereo, mono→stereo
- [ ] Смена sample rate не роняет и не даёт щелчков
- [ ] pluginval strictness 10 зелёный
- [ ] Ни одной аллокации в аудиопотоке

---

## [10] APVTS: параметры и сохранение состояния
**Labels:** architecture
**Milestone:** M1

### Описание
`AudioProcessorValueTreeState` со всеми параметрами MVP: delay time, sync on/off, note division,
feedback, mix, output gain, root key, pitch range, attack, release, voices, midi offset,
filter hi/lo, width. Сериализация в `getStateInformation`. Версионирование состояния,
чтобы будущие параметры не ломали старые проекты.

### Критерии приёмки
- [ ] Все параметры доступны для автоматизации в FL Studio
- [ ] Состояние переживает сохранение и загрузку проекта
- [ ] В состоянии есть номер версии, неизвестные поля игнорируются без падения
- [ ] Имена параметров человекочитаемы в списке автоматизации хоста

---

## [11] Dry/Wet, output gain, bypass без кликов
**Labels:** dsp
**Milestone:** M1

### Описание
Сглаженные параметры через `SmoothedValue`. Dry-путь семплово выровнен с wet.
Корректный bypass: хост может звать `processBlockBypassed`, хвост не должен обрываться щелчком.

### Критерии приёмки
- [ ] Резкое движение любого из трёх параметров не даёт щелчка
- [ ] При mix=0 выход бит-в-бит равен входу
- [ ] Bypass и обратно — без разрывов
- [ ] Dry и wet выровнены по времени (проверено на импульсе)

---

## [12] Приём MIDI с sample-accurate таймингом
**Labels:** midi
**Milestone:** M2

### Описание
Разбирать `MidiBuffer` с учётом sample offset каждого события. Блок обрабатывается сегментами
между MIDI-событиями, а не целиком с нотами в начале. Note on, note off, all-notes-off,
sustain pedal, pitch bend (в v1 можно игнорировать, но не падать).

### Критерии приёмки
- [ ] Голос стартует ровно на сэмпле события, а не на границе блока
- [ ] Тест: одинаковый результат при размерах буфера 64, 128, 512, 2048
- [ ] All-notes-off корректно гасит голоса с fade-out, не щелчком
- [ ] Неизвестные MIDI-сообщения игнорируются без падения

---

## [13] Voice manager: полифония и voice stealing
**Labels:** dsp, architecture
**Milestone:** M2

### Описание
Пул из N голосов, аллокация без выделения памяти в аудиопотоке. Стратегия кражи:
самый старый в фазе release, затем самый тихий. Отбираемый голос уходит с быстрым fade-out
(3–5 мс), чтобы не щёлкнуть. Лимит голосов — параметр.

### Критерии приёмки
- [ ] Аккорд из 4 нот даёт 4 независимо питченых хвоста
- [ ] Превышение лимита не даёт щелчков и не роняет плагин
- [ ] Ноль аллокаций при аллокации и краже голоса
- [ ] Стратегия кражи задокументирована в коде одной строкой комментария

---

## [14] Pitch shifter: dual-head varispeed
**Labels:** dsp
**Milestone:** M2

### Описание
Два ридера буфера, смещённых на пол-окна, читают с переменной скоростью, склеиваются
**equal-power** кроссфейдом (не линейным — линейный даёт провал громкости в центре).
Окно 50–80 мс для голоса. Реализовать за интерфейсом `PitchShifter` из ADR #6.

### Критерии приёмки
- [ ] Сдвиг на ±12 полутонов работает без разрывов и без провалов громкости
- [ ] Кроссфейд equal-power, проверено на синусе: RMS постоянен в течение перехода
- [ ] Внутренняя латентность алгоритма известна и отдаётся вызывающему коду
- [ ] Слепое сравнение на вокале: артефакты приемлемы для тихого фонового слоя

---

## [15] Маппинг MIDI-ноты в pitch ratio (Relative / Root Key)
**Labels:** midi, dsp
**Milestone:** M2

### Описание
`semitones = midiNote − rootKey`, `ratio = 2^(semitones/12)`. Root Key — параметр
(нота + октава). Ограничение диапазона сдвига параметром Pitch Range, за пределами —
либо clamp, либо перенос на октаву внутрь диапазона (решить и записать).

### Критерии приёмки
- [ ] Нота, равная Root Key, даёт хвост без транспонирования
- [ ] Нота на октаву выше Root даёт ровно удвоение частоты (проверено измерением)
- [ ] Поведение за границей Pitch Range определено и задокументировано
- [ ] Смена Root Key на лету не роняет уже звучащие голоса

---

## [16] Огибающая голоса из velocity и длительности ноты
**Labels:** dsp, midi
**Milestone:** M2

### Описание
AR или ADSR на голос. Velocity → пиковая громкость (кривая настраиваемая, по умолчанию
что-то мягче линейной). Note off запускает release. Attack 5–20 мс скрывает большинство
транзиентных артефактов питчера — это дешёвая замена сложному алгоритму.

**Решено в сессии 10:** кривая velocity — `sqrt`, зашитая константа, а не параметр.
Velocity управляет энергией, а не амплитудой: мягче линейной, свободного числа
в корне нет, настраивать нечего. Форма фронтов: атака `1-(1-p)^2`, спад `p^2`,
кража осталась линейной (ADR 0001). Разбор — в `prompts/PROGRESS.md`, находки сессии 10.

### Критерии приёмки
- [x] Длина хвоста следует длительности MIDI-ноты
- [x] Velocity слышимо управляет громкостью хвоста
- [x] Attack и Release — параметры, короткие значения не дают щелчков
- [x] Очень короткая нота (< attack) не даёт щелчка и не залипает

---

## [17] Компенсация латентности: прячем алгоритм в delay time
**Labels:** dsp, architecture
**Milestone:** M2

### Описание
Ключевое из `docs/ANALYSIS.md` §5. Внутренняя латентность питчера вычитается из позиции
чтения: `readOffset = delayTime − algLatency`. Минимальный delay time равен `algLatency`.
`setLatencySamples(0)`, пока условие выполняется.

**Нижний предел зависит от движка (сессия 09, [ADR 0005](adr/0005-hq-pitch-engine.md)):**
у Fast это 5762 сэмпла (120 мс при 48 кГц), у HQ — 8640 (180 мс). Значит кламп
не константа, а функция активного значения Quality, и при переключении на HQ
уже выставленное короткое время надо подтягивать вверх — молча или с показом
в UI, но не оставлять как есть: сейчас смещение просто упирается в кламп
`Voice::setDelaySamples`, и хвост приходит позже заказанного.

**Решено в сессии 10:** подтягивается **эффективное** время в DSP, значение параметра
не трогается. Писать в параметр из плагина значило бы драться с автоматизацией хоста
и терять выставленные 120 мс при возврате на Fast. Предел спрашивается у движка
(`VoiceManager::getLatencySamples`) и показывается в окне плагина: строка про движок
становится оранжевой и говорит `delay time raised to min 180 ms`.

### Критерии приёмки
- [x] Плагин репортит нулевую латентность при delayTime ≥ algLatency
- [x] Реальная задержка хвоста измерена и совпадает с выставленной (±1 мс)
- [x] Минимальный delay time ограничен снизу и это видно в UI
- [x] Предел пересчитывается при смене Quality, а не зашит константой
- [x] Смена алгоритма питчинга не требует правок в вызывающем коде

---

## [18] Параметр MIDI Offset (±ms)
**Labels:** midi, daw-compat
**Milestone:** M2

### Описание
Калибровочный винт под реальные DAW. FL Studio компенсирует задержку MIDI-роутинга иначе,
чем Live или Logic, и «идеально по нулям» не будет никогда. Диапазон ±100 мс,
положительный сдвигает срабатывание ноты позже, отрицательный — раньше (требует
предвыборки, учесть в размере буфера).

### Критерии приёмки
- [x] Параметр есть в UI и в автоматизации
- [x] Отрицательный офсет работает, буфер под него зарезервирован
- [x] Рассинхрон в FL Studio выправляется этим параметром до слуховой точности
- [x] Рекомендованные значения для FL Studio записаны в документацию

**Сделано в сессии 11.** Диапазон ±100 как в описании. Главное решение — офсет двигает
**само MIDI-событие**, а не позицию чтения из кольца: слышно то, когда хвост начался,
а сдвиг чтения меняет только материал под уже начавшимся хвостом и на десятках
миллисекунд неразличим. Отсюда несимметричная цена: плюс стоит очереди событий,
минус придерживает сухой сигнал и репортится хосту. Разбор — [ADR 0006](adr/0006-follow-mode.md).

**Проверено в FL Studio 20.8.3** 9 сентября 2026: в режиме Free эхо попадает в долю
на офсете **0 мс**, подстройка не понадобилась. Это не удача — FL отдаёт события
с честным sample offset внутри блока, а плагин его уважает (ANALYSIS §6.1). Винт
остаётся на случай других хостов и версий. Таблица — [FL_STUDIO.md](FL_STUDIO.md), шаг 5.

---

## [19] End-to-end: вокал + MIDI → поющий хвост
**Labels:** test, dsp
**Milestone:** M2

### Описание
Момент истины всего проекта. Офлайн-рендер: вокальный файл + MIDI-мелодия на вход,
результат на диск. Слуховая оценка и честный вывод: убедительно или нет.
Если нет — вернуться к ADR #6 и пересмотреть движок питчинга **до** M3.

### Критерии приёмки
- [x] Скрипт офлайн-рендера воспроизводим одной командой
- [x] Результат сохранён в репозитории как референс (или ссылкой, если тяжёлый)
- [x] Написан честный вывод о качестве: что звучит, что нет — числовая часть; слуховая за сессией 12
- [x] Принято явное решение — идти дальше на этом движке или менять

**Частично сделано в сессии 09.** Рендер синтетического материала воспроизводим
одной командой обоими движками, зерно случайной фазы у HQ зафиксировано:
`ProcessorTest --render out.wav hq|fast`. WAV в репозиторий не кладётся намеренно —
детерминированная команда это более сильный референс, чем бинарник, который
устареет на первой же правке DSP. Решение о движке принято и оформлено
[ADR 0005](adr/0005-hq-pitch-engine.md): идём дальше на Signalsmith.

**Замер на живом вокале, сессия 11.** Пользователь отрендерил из FL три куска по 9 секунд:
чистый вокал и выход плагина в режиме Follow при MIDI Offset 0 и −100. Считалась взаимная
корреляция и остаток после вычитания сухого с подбором общего множителя.

| Что мерилось | Результат |
|---|---|
| Сдвиг подпевки относительно вокала | **0,00 мс**, во всех 18 окнах по 0,5 с, разброс нулевой |
| Корреляция на нулевом лаге | 0,94–0,95 |
| Остаток там, где подпевка звучит (28 окон) | **−25,5 dB** к сухому, лучшее окно −58 dB |
| Остаток там, где огибающая закрыта (14 окон) | −11,5 dB — это просто недостающая половина при Mix 50 |
| Спектр остатка | повторяет форму сухого примерно на 10 dB ниже во всех полосах |
| Автокорреляция остатка, 50–1000 мс | максимум 0,10 — эха нет, обратная связь была выключена |

Выводы, которые из этого следуют честно:

- **Тайминг в Follow идеальный.** Не «в пределах слуховой точности», а ноль сэмплов
  на живом материале в живом хосте. Ощущение микрозадержки, с которого начался разбор,
  таймингом не было.
- **На ratio 1.000 движок практически прозрачен:** во время удержанной ноты выход
  отличается от входа на −25 dB. Это верхняя граница качества, а не типичный случай.
- **Остаток по спектру — масштабированная копия сухого,** а не узкий артефакт. Значит
  это амплитудная модуляция огибающей голоса (подпевка появляется и уходит вместе
  с нотами), а не размазывание вокодера. Размазывание дало бы перекос в верх и в транзиенты.

### Замер на настоящей подпевке (ratio ≠ 1)
Второй заход: рендеры «разные ноты» в обоих режимах. Подпевка изолирована вычитанием
сухого с подобранным множителем, высота обоих сигналов снята YIN, интервал сравнён
с ближайшим точным полутоном.

| Режим | Окно движка | Медиана \|отклонения\| | 90-й процентиль | На октаве (+12) |
|---|---|---|---|---|
| Free, HQ | 0,18 с | **3,7 ц** | 28,8 ц | +0,5 ц |
| Follow, тогдашний свой движок | 0,09 с | **20,7 ц** | 42,7 ц | −11,6 ц |

Заодно подтвердилось, что в Free задержка хвоста ровно 400 мс — то, что и выставлено
параметром.

**Из этого замера отменено проектное решение:** отдельный короткий движок под Follow
удалён, режим работает на движке, выбранном Quality. Разбор — [ADR 0006](adr/0006-follow-mode.md),
раздел «Отмена».

### Контрольный замер после отмены
Пользователь перезапустил FL и отрендерил Follow заново на исправленной версии. Сравнение
честнее вести по кадрам, где интервал реально не нулевой: в бине «0 полутонов» сидят
остатки сухого, которые меряются как ровный ноль и занижают общее число.

| Рендер | Окно движка | Медиана \|отклонения\|, только транспонированные кадры |
|---|---|---|
| Free, HQ | 0,18 с | 8,5 ц |
| Follow, отменённый движок | 0,09 с | **24,0 ц** |
| Follow, после правки | 0,18 с | **10,0 ц** |

Follow сравнялся с Free, остаток разницы — в пределах шума выборки (73 кадра против 213).
Отмена подтверждена.

### Честный вывод о качестве, числовая часть
- **Тайминг безупречен.** В Follow подпевка стоит на сухом с точностью 0,00 мс, в Free
  хвост приходит ровно на выставленные 400 мс. Проверено в живом хосте, не в тесте.
- **Интонация на живом вокале — около 8–10 центов медианы**, 90-й процентиль под 30.
  Это втрое хуже, чем на синтетических тонах (3,2 ц), и разница не в движке, а в материале:
  вибрато, согласные и переходы бьют по фазовому вокодеру сильнее, чем установившийся синус.
  Десять центов на подпевке в миксе — приемлемо; в жёстком унисоне на длинной ноте
  это уже слышно биениями.
- **Прозрачность на ratio 1.000 — минус 25,5 dB**, в лучшем окне минус 58.
- **Артефактов сверх этого не видно:** остаток по спектру повторяет форму сухого,
  узких выбросов и эха нет.

### Слуховая часть, сессия 12
Материал для офлайн-рендера — два файла, и они дают разные ответы:

- `~/Downloads/audio [vocals].wav` — пение, тот же материал, что мерился в сессии 11;
- `~/Downloads/Мастерская по ремонту обуви 6.wav` — **речь**, выбрана пользователем как
  основной материал. Несмотря на расширение, внутри AAC; `renderDemo` читает его через
  `CoreAudioFormat`, а не через `registerBasicFormats`.

**Кусок выбирается по плотности речи, а не с начала файла.** Дикторская запись — это
сессия с дублями: у этой первые семь секунд комната, потом фраза, потом ещё семь секунд
паузы. Рендер с начала файла вышел бы на 40 % тишиной, и слушать в нём было бы нечего.
`renderDemo` режет запись на кадры по 250 мс, считает порог как четверть от девяностого
процентиля уровня и берёт то окно, где кадров выше порога больше всего. На этом файле
выбирается кусок с 18,8 с, где речи 97 %.

`renderDemo` научился читать звук с диска, путь — аргументом:

```
ProcessorTest --render out.wav [fast|hq|follow] [input.wav] [colour]
```

Mix 100 %, мелодия крутится по кругу (C5, E5, G5, C6 в номерах FL, то есть унисон,
терция, квинта, октава), первые 30 секунд файла. Без `colour` диффузия и фильтры петли
выключены — рендер судит питчер, а не обвязку.

**Транзиенты замерены, а не только услышаны.** Крутизна атаки — 90-й процентиль
производной огибающей (окно 8 мс, шаг 2 мс) на кадрах, где нота звучит; корреляция
огибающих — между сухим и хвостом, выровненными по латентности движка.

| Рендер | Интервал | Корр. огибающих | Крутизна атаки, хвост / сухой |
|---|---|---|---|
| Follow, HQ | унисон | 0,999 | 99 % |
| Follow, HQ | +4 пт | 0,962 | 97 % |
| Follow, HQ | +7 пт | 0,970 | 78 % |
| Follow, HQ | +12 пт | 0,964 | 72 % |
| Free, HQ | унисон | 0,976 | 95 % |
| Free, HQ | +4 пт | 0,951 | 93 % |
| Free, HQ | +7 пт | 0,965 | 82 % |
| Free, HQ | +12 пт | 0,963 | 85 % |
| Free, Fast | унисон | 0,934 | 104 % |
| Free, Fast | +4 пт | **0,739** | 90 % |
| Free, Fast | +7 пт | **0,680** | 82 % |
| Free, Fast | +12 пт | 0,897 | 90 % |

### Речь оказалась вдвое более жёстким материалом
Тот же замер на дикторской записи. У речи атаки сами по себе вдвое круче, чем у пения
(3,4 против 1,8 dB на 2 мс в сухом), и питчер срезает их сильнее:

| Рендер | Интервал | Корр. огибающих | Крутизна атаки, хвост / сухой |
|---|---|---|---|
| Follow, HQ | унисон | 1,000 | 99 % |
| Follow, HQ | +4 пт | 0,969 | **63 %** |
| Follow, HQ | +7 пт | 0,970 | **54 %** |
| Follow, HQ | +12 пт | 0,955 | 60 % |
| Free, HQ | унисон | 0,955 | 87 % |
| Free, HQ | +4 пт | 0,964 | 58 % |
| Free, HQ | +7 пт | 0,963 | 53 % |
| Free, HQ | +12 пт | 0,941 | 85 % |
| Free, Fast | унисон | **0,815** | 92 % |
| Free, Fast | +4 пт | **0,728** | 62 % |
| Free, Fast | +7 пт | **0,788** | 63 % |
| Free, Fast | +12 пт | **0,824** | 91 % |

**У HQ корреляция огибающих при этом не падает — держится 0,94–0,97.** То есть хвост
не опаздывает и не разъезжается со слогами; он именно скругляет фронт. На пении такое
скругление незаметно, потому что там и в сухом фронты пологие. На речи — вопрос к уху,
и цифра «48 % крутизны» его не заменяет ни в какую сторону: половина от очень крутого
фронта может остаться вполне внятной согласной.

Практический вывод для всех будущих замеров: **порог, снятый на пении, на речи неверен
вдвое.** Материал надо называть рядом с числом.

Что следует из обоих замеров:

- **Атака размывается предсказуемо и умеренно.** На унисоне хвост повторяет атаку
  сухого один в один, на октаве теряет 15–28 % крутизны. Это фазовый вокодер,
  и это ровно то, чего от него ждут: не «сохраняет транзиенты», но и не превращает
  согласную в шелест.
- **Fast разваливает не атаку, а тайминг.** Крутизна у него даже выше HQ (варигонка
  не размывает, она пересэмплирует), а корреляция огибающих на терции и квинте падает
  до 0,68–0,74: сегмент проигрывается с другой скоростью, и слоги хвоста разъезжаются
  с сухим. На слух это «хвост не в такт», а не «хвост мутный». Ещё один довод за HQ
  по умолчанию, независимо от ADR 0005, где решение принималось по расстройке.
- **Доля энергии 4–10 кГц на унисоне не меняется** (±0,1 дБ в Follow): согласные
  не глотаются и не подчёркиваются.

### Слуховой вердикт: получен, задача закрыта
Пользователь послушал рендеры на дикторской записи и сказал: **проблем не слышно
ни на чистом HQ, ни с окраской, ни на Fast.** Отдельно — что от фильтров в петле
не стало глухо.

Из этого следует ровно то, что следует, и не больше:

- **ADR 0005 остаётся в силе**, разбирать движок питчинга заново не на чем.
- **Потеря 40–47 % крутизны фронта на транспонированных нотах ухом не читается
  как дефект.** Это стоит запомнить: замер видит разницу там, где её нет слышно,
  и следующий раз, когда цифра испугает, надо сперва послушать.
- **Разрыв между Fast и HQ на речи (корреляция огибающих 0,73 против 0,96) тоже
  не читается.** То есть основание держать HQ движком по умолчанию — расстройка
  из ADR 0004 и ADR 0005, а не тайминг. Метрика огибающих оказалась чувствительнее уха.

Материал остаётся в `~/Downloads/S12-renders/`: `01` и `03` — голый питчер на HQ и Fast,
`02` и `05` — плагин на значениях по умолчанию в обоих режимах времени, `04` — голый
питчер в Follow.

---

## [20] Tempo sync: нотные длительности
**Labels:** dsp, midi
**Milestone:** M3

### Описание
`AudioPlayHead::PositionInfo` → BPM. Делители от 1/1 до 1/32, плюс dotted и triplet.
Переключатель Sync / Free (мс). Смена делителя на ходу не должна рвать звучащие хвосты —
применять либо с кроссфейдом, либо на границе следующей ноты (решить и записать).

### Критерии приёмки
- [x] Задержка совпадает с сеткой проекта на 60, 120 и 174 BPM (проверено измерением)
- [x] Dotted и triplet считаются верно
- [x] Отсутствие playhead (например, в Standalone) не роняет — фолбэк на 120 BPM
- [x] Смена делителя во время звучания не даёт щелчка

### Сделано в сессии 14

**Sync — галка, а не третий пункт Time Mode.** Развилка решалась до кода, как и требовал
промпт. Довод за список («режим времени один») проигрывает одному факту: Sync и Time Mode
отвечают на разные вопросы. Sync — «чем задано время»: миллисекундами с ручки или нотной
длительностью от темпа. Time Mode — «откуда хвост читает»: из прошлого (Free) или из
настоящего (Follow, ADR 0006). Третий пункт списка запретил бы Follow вместе с сеткой,
хотя интервал повторов обратной связи в Follow есть и держать его нотной длительностью
осмысленно ровно так же. Побочно: галка не ломает сохранённые проекты, а третий пункт
менял бы смысл индекса 2 в списке.

**Включена по умолчанию, и Delay Time стал 500 мс вместо 400.** Прежние 400 не попадали
ни в одну сетку при 120 BPM (восьмая 250, четверть 500), то есть значение по умолчанию
промахивалось мимо главного сценария плагина. Теперь при 120 BPM ручка, делитель 1/4
и сетка дают одно и то же число, и выключение Sync не двигает звук.

**Темп снимается и в `prepareToPlay`, не только в `processBlock`.** Без этого первый блок
после подготовки работал на фолбэке, а голос берёт позицию чтения один раз на сегмент —
и хвост выходил **дважды**: один раз по старому времени, один по новому. На блоке 512
сэмплов это 10 мс, на 16384 — треть секунды. Замер поймал сразу: два импульса, на 24000
и на 48000 сэмплах вместо одного.

**Границы темпа 20..999 BPM.** Это граница доверия к хосту: ноль или отрицательный темп
уронил бы сетку в бесконечность, и молча. Проверены четыре способа не получить темп —
playhead нет вовсе (Standalone), playhead есть без BPM, BPM ноль, BPM отрицательный.

**Смена делителя на звучащей ноте — разрыв 0,84 при пороге 0,05, и он был настоящий.**
Причина не в Sync: голос — это отвод кольца, и он прыгал вслед за ручкой Delay Time
с сессии 05, просто до #20 некому было дёрнуть время музыкально. Починка — в описании
самой задачи («либо с кроссфейдом, либо на границе следующей ноты»): `VoiceManager::
setDelaySamples` теперь только запоминает число, а голос забирает его в `noteOn`
и держит до конца ноты. Кроссфейд стоил бы второго питчера на голос.

**Что при этом осталось и объявлено.** Петля обратной связи время по-прежнему меняет
на ходу, и на большом скачке это ленточный «зип»: время едет 12000 → 48000 сэмплов
за 50 мс, то есть позиция чтения идёт назад в четырнадцать раз быстрее, чем вперёд идёт
запись. Разрыва там нет — есть высокая частота, и детектор производной её от щелчка
не отличает. Механизм тот же, на котором стоит модуляция (#46); отменить его — значит
отменить ленточный характер.

---

## [21] Feedback без кумулятивного питч-дрейфа
**Labels:** dsp
**Milestone:** M3

### Описание
Feedback берётся **до** питч-стадии: в буфер возвращается чистый сигнал. Иначе каждый круг
транспонирует хвост заново и подклад уползает по высоте (эффект Шепарда). Опционально —
переключатель Pitched Feedback для тех, кому этот уползающий эффект нужен как приём.

### Критерии приёмки
- [x] При feedback > 0 высота повторов не уползает
- [~] Feedback = 1.0 не даёт самовозбуждения — единицы у пользователя нет, потолок 95 %;
      проверено то, что за критерием стоит: на 95 % петля идёт вниз, а не разгоняется
- [x] Переключатель Pitched Feedback не сделан и не нужен — обоснование ниже
- [x] Хвост затухает предсказуемо и полностью

### Закрыта замером в сессии 14

Сама реализация стоит с сессии 09 — feedback снимается до питч-стадии, это инвариант
в CLAUDE.md. Не хватало замера, и в сессии 14 он сделан: короткий тон 220 Гц, нота
октавой вверх (ratio 2), feedback 90 %, четыре круга подряд.

| Круг | Высота | Уровень |
|---|---|---|
| 1 | 440,0 Гц | 0,3553 |
| 2 | 440,0 Гц | 0,3187 |
| 3 | 440,0 Гц | 0,2863 |
| 4 | 440,0 Гц | 0,2583 |

Высота не двигается ни на герц, уровень идёт строго вниз с шагом 0,90 — то есть ровно
feedback. Если бы feedback снимался после питчера, круги дали бы 440, 880, 1760, 3520 —
эффект Шепарда, и он ушёл бы за границу поиска на втором же круге.

**Pitched Feedback не сделан намеренно.** В описании он «опционально», и это ручка,
которая делает единственную вещь — ломает инвариант. Кому нужен уползающий подклад,
тот ставит второй экземпляр плагина в цепь. YAGNI.

**Про самовозбуждение.** Буквально критерий проверить нельзя: потолок параметра 95 %,
единицы нет. На 95 % замерено затухание (круг 2 — 0,3364, круг 6 — 0,2743). Мягкое
ограничение в петле осталось в #44 и осмысленно ровно тогда, когда есть куда разгоняться.

---

## [22] Фильтры хвоста (HP/LP)
**Labels:** dsp
**Milestone:** M3

### Описание
Hi-pass и low-pass в тракте хвоста — чтобы подклад «отодвигался» назад и не спорил с основным
вокалом. Это то, ради чего пользователь и ставит плагин: слой должен быть слышен, но не заметен.
Фильтры в петле feedback (тогда каждый круг темнее) или после — решить и записать.

### Критерии приёмки
- [x] HP и LP работают, коэффициенты пересчитываются при смене sample rate
- [x] Крутка частоты среза не даёт зиппера (сглаженные коэффициенты)
- [x] Позиция фильтра относительно петли feedback задокументирована
- [x] На дефолтных значениях подклад заметно уходит назад в миксе

### Сделано в сессии 12

**Позиция: на входе кольца, то есть в петле.** `lineIn = dry + feedback` проходит
однополюсники до записи в кольцо. Значит первый хвост окрашен один раз, второй два,
пятый пять — хвост темнеет с каждым кругом. Две альтернативы отвергнуты:

- *на выходе wet* — это просто эквалайзер, который пользователь и снаружи повесит,
  и с кругами он ничего не делает;
- *только на возврате обратной связи* — тогда при feedback 0 фильтры не делают ничего,
  и критерий «на дефолтах подклад уходит назад» не выполняется вовсе.

Проверяется тем, чем эти схемы и различаются: сколько добавляет обратная связь.
Синус 6 кГц, интервал повтора — целое число периодов, повторы складываются в фазе.
Без фильтра включение feedback 80 % поднимает уровень в **5,0 раза**, с LP на 2 кГц
в петле — в **1,35 раза**. Фильтр на выходе дал бы 5,0 в обоих случаях.

**Однополюсные, без резонанса.** `a = 1 - exp(-2*pi*f/fs)`, коэффициент сглаживается
теми же 50 мс, что и остальные величины: `exp()` на каждый сэмпл дорог, а зиппер слышен
одинаково что от частоты, что от коэффициента. Резонансный биквад в петле при
feedback 95 % — классический способ получить свист, и заводить его без замера усиления
петли не за чем.

**На краях диапазона фильтр обходится целиком.** Однополюсник, поставленный на 20 кГц,
всё ещё срезает импульс почти на децибел, поэтому 20 Гц и 20 кГц — это положение
«выключено», а не «почти прозрачно». Тесты, которые меряют тайминг и уровни, ставят
именно эти значения (`plainLoop` в `test_processor.cpp`).

Значения по умолчанию 100 Гц / 12 кГц режут край не меньше чем на 3 dB уже на первом
круге — это и есть «подклад уходит назад», и на это есть тест. Проверено и на слух:
пользователь послушал рендер на значениях по умолчанию и сказал, что глухо не стало.

---

## [23] Стерео: ширина, пан голосов, ping-pong
**Labels:** dsp
**Milestone:** M3

### Описание
Параметр Width. Опционально — пан на голос (например, по номеру ноты или по кругу),
что само по себе создаёт объём без реверба. Ping-pong как отдельный режим.
Обязательно проверить моносовместимость: подклад не должен исчезать в моно.

### Критерии приёмки
- [x] Width от 0 (моно) до 100% работает плавно
- [x] Корреляция в моно проверена, фазового вычитания нет
- [x] Ping-pong (если сделан) чередует каналы ровно
- [x] Моно-вход + стерео-выход даёт широкий подклад из моно-источника

### Ping-pong сделан в сессии 13, но не тот, что в описании

**Классический ping-pong в этой архитектуре не слышен вовсе.** Чередование повторов
обратной связи живёт в кольце, а наружу хвост выходит только через голоса — и голос
читает **моно-сумму** кольца, потому что питчер у него один, а стерео он делает паном
(ADR 0001). Что бы кольцо ни чередовало, голос усреднит это обратно в центр. Проверять
это замером не пришлось: достаточно посмотреть на `Voice::addTo`.

**Сделано чередование нот.** Для MIDI-ведомого дилея оно и осмысленнее: мелодия
монофонная, ноты идут по очереди, и разлёт попадает в её ритм, а не в интервал повторов.
Замер: две ноты подряд дают баланс -0,41 и +0,41 при Width 100 %, без ping-pong обе
идут одинаково. Размах берётся от Width — отдельной ручки нет, иначе в окне стояли бы
две ручки ширины, и вторая объяснялась бы только тем, что первая работает в другом режиме.

**Сторона сбрасывается на выключении, а не на включении:** тогда первая нота после
включения всегда уходит влево, и эффект начинается предсказуемо.

**Замер моносовместимости сделан в сессии 14.** Мерилась корреляция каналов и уровень
моно-суммы против среднего уровня каналов, на значениях по умолчанию и с дрейфом:

| Настройки | Корреляция | Моно-сумма |
|---|---|---|
| Width 100, Diffusion 50 | +0,987 | −0,03 dB |
| Width 200, Diffusion 50 | +0,950 | −0,11 dB |
| Width 200, Diffusion 100 | +0,950 | −0,11 dB |
| Width 100, ping-pong, Diffusion 50 | +0,706 | −0,69 dB |
| Width 150, ping-pong, Diffusion 50 | +0,381 | −1,61 dB |
| Width 200, ping-pong, Diffusion 100 | −0,002 | **−3,02 dB** |

**Фазового вычитания нет нигде** — для него нужна отрицательная корреляция, а её нет:
худшее значение это ноль. Диффузор, разведший каналы по длинам звеньев, моносовместимость
не испортил: без ping-pong корреляция держится выше 0,95, и в моно теряется десятая доля
децибела. Опасение сессии 13 не подтвердилось.

**Край — Width 200 с ping-pong: −3,02 dB, и это пол, а не дефект.** Корреляция ровно
ноль означает, что борта несут разные ноты и никак не связаны, а две некоррелированные
половины при сложении и должны дать −3 dB. Ниже увести может только противофаза.
Практическое следствие для пресетов (#48): подклад, рассчитанный на клуб или радио,
не должен стоять на Width 200 вместе с ping-pong — в моно он потеряет ровно вдвое
по мощности. На Width 100 с ping-pong потеря 0,7 dB, и это уже незаметно.

**Width 150 домерен в сессии 15, потому что он стоит в пресете Sung Vocal.** −1,61 dB,
то есть больше половины пути к физическому полу. Значение оставлено: 150 одобрено ухом
в сессии 13, а замер здесь описывает цену, а не выносит вердикт — это тот самый порядок
«ухо главнее», который в проекте не нарушается. Если на рендерах сессии 15 моно окажется
важнее ширины, замена одна: `width` в пресете `sungVocal` на 100.

**Вердикт сессии 17: в `sungVocal` поставлено `width` 100.** Вопрос был задан прямо —
ширина или моносовместимость, — и пользователь выбрал моно: «чтобы не пропадало в моно».
Цена решения обратна замеру выше: потеря в моно падает с 1,61 dB до 0,69 dB, стерео-разлёт
остаётся, потому что его делает сам ping-pong, а не Width. Одобрение уха из сессии 13
относилось к 150 без вопроса о моно; заданный вопрос его отменил, и это тот же порядок
«ухо главнее замера» — замер лишь назвал цену, вердикт вынес человек.

Замер стоит в `test_processor.cpp`, раздел «Моносовместимость», и держит границу:
порог по корреляции ловит вычитание, порог −3,1 dB ловит уход ниже физического пола.

**Половина сделана в сессии 11** — пользователь сказал, что звучит сухо и плоско,
а пан в голосе был прошит насквозь и просто не задействован. Width раскидывает голоса
по номеру слота: нулевой в центре, дальше через одного вправо и влево. Порядок именно
такой, потому что одиночная нота почти всегда попадает в нулевой слот и обязана
остаться по центру. Пан равномощный, ширина 0 % возвращает прежнее моно.

**Осталось:** ping-pong, замер моносовместимости, фильтры хвоста живут в [#22](#22).

### Сессия 18: вердикт по паре рендеров не получен

`s17-1-sung-vocal-width100.wav` против `s17-2-...-width150.wav` оставлены сессией 17
как A/B к уже принятому решению. Ответ не пришёл — вопрос задан второй раз.
Пресет остаётся на **Width 100**: решение принято замером моно-суммы (потеря падает
с 1,61 dB до 0,69 dB), и без слухового возражения его менять не на чем.

### Сессия 19: вопрос снят — ответа нет в третий раз

A/B `s17-1` против `s17-2` не услышан и в третий раз. Пользователь сам предложил
снять вопросы, если слушать некогда, а не возить их из сессии в сессию. **Вопрос
снят.** Width 100 в Sung Vocal остаётся: это решение сессии 17, принятое словами
пользователя («чтобы не пропадало в моно»), и A/B лишь подтвердил бы его ухом.
Вернуться, только если на Sung Vocal придёт жалоба «узко».

### Сессия 21: тот же замер для Stereo Mode ([#55](#55))

Галка ping-pong стала списком Stereo, и замер перемерен на тех же настройках, с прототипами
обеих развилок. Choir — прежний разлёт по слотам, цифры те же. Ping-Pong по нотам чуть лучше
прежнего: нота в тишину теперь уходит в центр.

| Настройки | Корреляция | Моно-сумма |
|---|---|---|
| Width 100, Choir, Diffusion 50 | +0,987 | −0,03 dB |
| Width 200, Choir, Diffusion 50 | +0,950 | −0,11 dB |
| Width 200, Choir, Diffusion 100 | +0,950 | −0,11 dB |
| Width 100, Ping-Pong по нотам, Diffusion 50 | +0,730 | −0,63 dB |
| Width 150, Ping-Pong по нотам, Diffusion 50 | +0,428 | −1,46 dB |
| Width 200, Ping-Pong по нотам, Diffusion 100 | +0,066 | −2,72 dB |
| Width 100, хор парой, Diffusion 50 | +0,711 | −0,68 dB |
| Width 200, хор парой, Diffusion 100 | +0,019 | −2,93 dB |
| Width 100, классический ping-pong, Diffusion 50 | +0,768 | −0,48 dB |
| Width 200, классический ping-pong, Diffusion 100 | **−0,192** | −2,93 dB |

**Отрицательная корреляция у классического ping-pong — свойство режима, а не дефект.**
Он разводит соседние повторы по разным каналам, а соседние повторы установившегося тона
сдвинуты на delay time: 330 Гц на 250 мс — это 82,5 периода, ровно противофаза. Контроль:
на 240 мс та же строка даёт +0,078 и −2,10 dB, прочие сдвигаются на сотые. На живом материале
это слышно как провал отдельных нот в моно, если время совпало с полупериодом. Проверка
корреляции с классического снята, пол −3,1 dB по сумме остаётся на всех строках.

### Сессия 22: после вердикта по #55

Choir теперь пара голосов на ноту, классический ping-pong удалён, и проверка корреляции
снова стоит на всех строках. Ping-Pong по нотам не менялся — цифры те же.

| Настройки | Корреляция | Моно-сумма |
|---|---|---|
| Width 100, Choir (пара), Diffusion 50 | +0,711 | −0,68 dB |
| Width 200, Choir (пара), Diffusion 50 | +0,007 | **−2,98 dB** |
| Width 200, Choir (пара), Diffusion 100 | +0,019 | −2,93 dB |
| Width 100, Ping-Pong по нотам, Diffusion 50 | +0,730 | −0,63 dB |
| Width 150, Ping-Pong по нотам, Diffusion 50 | +0,428 | −1,46 dB |
| Width 200, Ping-Pong по нотам, Diffusion 100 | +0,066 | −2,72 dB |

**Цена пары в моно — та же, что у Sung Vocal.** Chord Pad на Width 100 терял в моно 0,03 dB,
теперь 0,68 — столько же, сколько ping-pong, принятый вердиктом сессии 17. Width 200 с парой
стоит в 0,12 dB от пола: две некоррелированные половины по бортам и должны дать −3 dB, ниже
уводит только противофаза, а её держит проверка корреляции.

---

## [24] Ограничение диапазона питча и защита от «бурундука»
**Labels:** dsp
**Milestone:** M3

### Описание
Параметр Pitch Range ограничивает сдвиг. За границей — либо clamp, либо октавный перенос
внутрь диапазона. Опция Formant Hold в MVP не реализуется, но интерфейс не должен ей мешать.
На больших сдвигах вверх — мягкий LP, чтобы шипящие не превращались в свист.

### Критерии приёмки
- [x] Сдвиги за пределами диапазона обрабатываются по задокументированному правилу
- [ ] Сдвиг +12 полутонов на вокале звучит приемлемо для фонового слоя
- [x] Шипящие на больших сдвигах вверх не режут ухо
- [x] Место под formant preservation в интерфейсе оставлено

### Сделано в сессии 13

**Компенсация формант оказалась переключателем, а не режимом.** Параметр `Formants:
Shift | Hold`. По умолчанию **Shift** — и это умолчание поставлено ухом против замера.

Замер говорит однозначно: Hold держит формантную область на месте, Shift уносит её вверх
вдвое, то есть делает ровно тот бурундук, ради которого задача заведена. Пользователь
послушал оба рендера и сказал: Shift лучше. Правдоподобное объяснение — Hold на октаве
вверх тише на 6 dB и темнее (компенсация срезает верх, который при Shift оставался),
и хвост уходит в кашу вместо того, чтобы читаться отдельным слоем. **Для фонового слоя
яркость важнее анатомической правильности голоса**, а «бурундук» на тихом хвосте
читается как эффект, а не как дефект.

Это третий случай подряд, когда ухо расходится с замером, и второй — когда оно
расходится с ним по знаку. Hold остаётся ручкой: на длинных нотах и небольших сдвигах
он ближе к голосу, и для синтетического источника выбор тоже не очевиден.

Обе настройки работают **только на HQ**, и это не недоделка: варигонка растягивает спектр
целиком, формант для неё физически не существует. Разница Fast и HQ — разница характера,
а не «быстрый и медленный».

**Замер вместо уха.** «Бурундук» выражен числом: доля энергии выше 1,2 кГц в хвосте
на октаве вверх. На модели гласной (пила 120 Гц через резонаторы 700/1200/2600 Гц)
Hold даёт 0,002, Shift — 0,075, то есть энергия уезжает вверх в 37 раз сильнее.
Первый заход мерил центр тяжести на пиле через фильтр — и показал противоположное:
у материала без формант компенсации нечего держать, и замер мерил что угодно, кроме
проверяемого. **Материал для замера формант обязан иметь форманты.**

**Предел тональности 8 кГц** включён у HQ всегда, не переключателем. Выше него частоты
не умножаются, а сдвигаются на постоянную величину: тон 6 кГц на октаве вверх приходит
на 11 657 Гц, а не на 12 000. Это и есть «шипящие не режут ухо» — «с» это шум в полосе
5-10 кГц, и честное транспонирование уносило бы его в свист. Число в API библиотеки —
доля sample rate, а не герцы: `tonalityLimit = 8000 / sr`.

**Цена: +34 % к HQ.** Восемь транспонированных голосов, 48 кГц, блок 512: 3,2 % ядра
без компенсации, 4,3 % с ней (Fast — 0,6 %). Бюджет ADR 0005 — 10,1 %, но он снят
на другой машине: там же и тогда HQ стоил 10,1 %, здесь базово 3,3 %. Сопоставимо
относительное число, и оно втрое ниже потолка. Замер повторяем: `ProcessorTest --bench hq hold`.

Компенсация стоит **только на транспонированных голосах** — внутри библиотеки она
включается как `formantCompensation && mappedFrequencies`, а второе истинно только при
`freqMultiplier != 1`. На унисоне даром. Поэтому мерить надо аккорд из восьми разных нот,
а не одну ноту восемь раз.

**Побочное следствие, которое надо знать:** Hold на октаве вверх тише примерно на 6 dB.
Это не дефект — компенсация возвращает спектральную огибающую на место и срезает то,
что при Shift оставалось наверху. Компенсировать гейном не стали: это была бы попытка
вернуть ровно ту энергию, которую переключатель убрал нарочно.

---

## [25] Анти-клик: границы голосов и смена параметров
**Labels:** dsp
**Milestone:** M3

### Описание
Ревизия всех мест, где сигнал может разорваться: старт и стоп голоса, voice stealing,
скачок delay time, смена sample rate, bypass, wrap кольцевого буфера, кроссфейд питчера.
Каждое место либо сглажено, либо явно помечено как безопасное.

### Критерии приёмки
- [x] Стресс-тест: случайные MIDI-ноты и рывки параметров 5 минут — ни одного щелчка
- [x] Пиковый детектор в тесте не ловит разрывов производной
- [x] Все найденные места перечислены в комментарии или в issue
- [x] Проверено на трёх sample rate: 44.1, 48, 96 кГц

### Сделано в сессии 14

**Детектор пришлось переделать, и это половина работы.** Голый максимум производной
не отличает щелчок от высокой частоты: смена времени при обратной связи даёт сплошной
ленточный «зип», где велики все шаги подряд, и порог по максимуму краснел бы на исправном
плагине (0,46 при пороге 0,05, и в осциллограмме никакого разрыва). Щелчок — это выброс:
один шаг много больше остальных. Меряется поэтому **отношение худшего шага к 99,9-му
процентилю**. Второе: шаг берётся за одинаковое **время**, а не за один отсчёт, — иначе
на 96 кГц гладкий сигнал даёт вдвое меньший шаг, а разрыв не даёт, и отношение раздувается
само собой (12,6 против 4,4 на том же звуке).

**Итог стресса:** 48 кГц / 300 с — 3,5; 44,1 кГц / 30 с — 5,2; 96 кГц / 30 с — 5,1
при пороге 8. На исправном плагине отношение держится около двух-трёх, щелчок даёт
десятки — поймали два, оба ниже.

**Найдено и починено: обход фильтров петли переключался мгновенно.** Low Cut и High Cut
на краю диапазона обходились булевым флагом, и флаг флипал на границе блока разом.
Вход кольца при этом прыгал ровно на накопленное состояние фильтра. Наружу это выезжало
позже и не на границе блока — через голос, — и выглядело как склейка посреди хвоста,
а не как щелчок фильтра. Замер: рывки Low Cut давали шаг 0,28 при фоне 0,013, отношение
22 против полутора у всех остальных параметров; на минимальной цепочке (один голос,
ничего в петле) — те же 22 на Fast и 11,6 на HQ, то есть движок ни при чём.
Починено двумя вещами сразу, и обе нужны: однополюсники **крутятся всегда** (замороженное
состояние держит кусок звука, который был в петле минуту назад), а результат
**подмешивается сглаженным множителем** (`loMixSmoothed`, `hiMixSmoothed`) вместо
мгновенного флага. Та же схема, что у `blend` диффузора. После починки — 1,3.

**Найдено и починено: скачок delay time.** Разрыв 0,84. Разбор и решение — в #20.

**Объявлено безопасным: смена Time Mode и отрицательный MIDI Offset.** Оба меняют
выравнивание всего плагина, то есть репортуемую хосту латентность, и сухой сигнал
начинает читаться с другого места. Замер: шаг 1,53 при фоне 0,05. Снять этот разрыв
внутри плагина нельзя и не нужно — в тот же момент пересобирает свою компенсацию
задержек и хост. Это два объявленных исключения ADR 0006, и третьим они не обрастают.
Положительная половина MIDI Offset выравнивание не двигает и в стресс входит.

**Полный список мест разрыва** — в комментарии к разделу «Анти-клик» в
`Source/test_processor.cpp`: там каждое место с указанием, чем закрыто и где замер.

### Сессия 23: стресс покраснел на Windows — открыто

CI, run 34752232973, MSVC: **48 кГц, 300 с — худший шаг 0,8939, 99,9 % 0,0923, отношение 9,7**
при пороге 8. На macOS тот же тест, та же сборка — 0,4985 / 0,1017 / 4,9, локально и в CI
одинаково. Зерно фиксировано, но 99,9 % разные: траектория сигнала на MSVC разошлась
(петля и случайные рывки раздувают разницу младших бит, как у Lo-Fi в [#34](#34)),
и на ней выпал другой худший случай. **Щелчок это или разброс — неизвестно:** тест
не печатает, какой параметр дёрнули перед худшим шагом. Для сравнения: исправленный
скачок delay time давал 0,84. Первый шаг следующей сессии — печатать id последнего рывка
и номер блока при худшем шаге и искать траекторию под Rosetta (x86_64), а не гадать.

### Сессия 24: настоящий дефект, найден и починен

**Траектория разошлась не в младших битах, а в порядке вычисления аргументов.**
`midi.addEvent (noteOn (..., random.nextFloat()), random.nextInt (blockSize))` — порядок
не определён стандартом: clang берёт velocity, потом offset, MSVC наоборот. На Windows
ноты стояли на других местах и с другой силой. Проверено прямо: на arm64 с переставленными
вызовами — худший шаг 0,9601, 99,9 % **0,0922**, отношение 10,4, и среди худших шагов
**0,8940**. MSVC: 0,8939 / 0,0923 / 9,7. Rosetta не понадобилась — это ближе, чем она.
Вызовы теперь разнесены по строкам в порядке clang: траектория одна на обоих
компиляторах, числа macOS не сдвинулись (4,9 до починки).

**Что это было — всплеск +16 dB на один блок, не разброс.** Тест теперь печатает три
худших шага с последними рывками и нотами. Блок 19853: пик 3,70 при соседях 0,5–0,6.
Форма гладкая, поэтому на шаг детектора это похоже слабо — но это «бум». Контрфактами
(выкинуть одно событие, выключить одну стадию за 10 блоков до): без рывка `delayTime`
в блоке 19835 — всплеска нет; без Formants Hold — нет; на Fast — втрое меньше;
при feedback 0 — остаётся, то есть кольцо ни при чём. По голосам: вход питчера v0 — 0,31,
выход — **3,05**.

**Механизм.** Голос украден, пока время едет рампой. По концу спада кражи он перезапускался
с новой позицией чтения (`readOffset` 0 → 14044), но без сброса питчера: окно хранило
историю со старого места, вход шёл с нового — склейка на входе питчера. Огибающая её
не прячет: ноль у неё в момент склейки на входе, а наружу склейка выходит через латентность
HQ (180 мс), когда атака (130 мс) уже доехала. HQ с Formants Hold раздувает её вдесятеро.
Тот же путь был у второго голоса хоровой пары: он читает со сдвигом, и кража голоса
с другим сдвигом склеивала бы и без поворота ручки.

**Починка — `Voice`.** Если кража меняет позицию чтения, сегмент режется ровно на конце
спада, питчер сбрасывается и заливается историей с нового места, как в `noteOn`. Если
не меняет — путь прежний бит-в-бит: эталоны #34 совпали с теми же запасами, `tests/regression`
не тронут. Отдельный тест сразу после стресса: один голос, HQ + Hold, время 200 → ~1500 мс,
кража, восемь целевых времён. Пик после кражи к пику до и после: **0,99 с починкой,
2,25 без неё**, порог 1,5.

**Стресс после починки:** порядок clang — 48 кГц 4,5; 44,1 — 1,1; 96 — 1,6 (было 4,9 / 1,1 / 3,6:
такие кражи были и там, просто ниже порога). Порядок MSVC — **3,7** вместо 10,4.
Порог не двигался. Рендеры до/после — `~/Downloads/BERG-S24/`, вердикт уха — сессия 25.

---

## [26] Каркас редактора и LookAndFeel
**Labels:** ui
**Milestone:** M4

### Описание
Редактор на JUCE, привязка контролов к APVTS через Attachment. Кастомный LookAndFeel:
плагин должен выглядеть как продукт, а не как демо из туториала. Группировка по смыслу:
Delay, Pitch, Envelope, Mix. WebView UI — избыточно, не брать.

### Критерии приёмки
- [x] Все параметры MVP доступны из UI
- [x] Двусторонняя связь с APVTS: автоматизация из хоста двигает контролы
- [x] Редактор открывается и закрывается многократно без утечек
- [x] Визуальная группировка отражает сигнальный путь
- [x] Кастомный LookAndFeel

**Половина сделана в сессии 11, вынужденно.** Пользователь сказал: «никаких настроек
в плагине не вижу» — и был прав, окно было отладочным табло вехи M0, а пятнадцать
параметров жили только в списке хоста. Проверять на слух что-либо в таком виде нельзя,
поэтому органы управления поставлены сразу: сетка 4 на 4, ручки/списки/галка строятся
по типу параметра, привязка через Attachment. Проверено `pluginval` (тесты Editor
и Editor Automation).

Намеренно **не** показаны `filterLo`, `filterHi` и `division`: они заведены в APVTS,
но ни к чему не подключены ([#22](#22), [#20](#20)), а мёртвая ручка в окне — это ложь.
Встанут в сетку одной строкой, когда их подключат.

### Закрыта в сессии 16

**Группы — это четыре полосы по сигнальному пути**, а не рамки вокруг случайных
соседей: `1 DELAY` (время, петля, её окраска), `2 PITCH`, `3 ENVELOPE`, `4 MIX`.
Порядок нумерован прямо в заголовке, потому что путь — это порядок, а не набор.
Сетка стала 5 колонок вместо 4: при четырёх группа Delay из десяти органов
разъезжалась на три ряда и переставала читаться одним куском.

**Ручки перестали врать, и это была настоящая причина задачи.** Три параметра
меняют смысл вместе с режимом, и раньше все они выглядели одинаково живыми:

| Орган | Когда мёртв или меняет смысл | Что делает окно |
|---|---|---|
| Delay Time | Sync включён — время задаёт делитель | гаснет ручка и число под ней |
| Delay Time | Follow — это интервал повторов, а не задержка | подпись `Repeat Time` |
| Note Division | Sync выключен | гаснет |
| Width | ping-pong — это разлёт нот, а не раскидка голосов | `Width - ping-pong` против `Width - spread` |

Правило одно: **погашенный орган гаснет вместе со своим числом**. Яркая цифра под
серой ручкой читается как «значение всё-таки действует», то есть ровно как та ложь,
ради которой всё затевалось. `Component::setEnabled` цвета не трогает, цвет ставится
руками.

**Quality в этот список не попал, хотя ROADMAP до сессии 16 утверждал обратное.**
Врезка «M4 подорожала» называла Quality третьим параметром, зависящим от режима:
«в Follow не действует». Это устарело — [ADR 0006](adr/0006-follow-mode.md) отменил
свой движок Follow замером расстройки, и качество там выбирается ровно как в Free.
Строчка в ROADMAP исправлена. Место третьего заняла Width при ping-pong.

**Своё оформление — `BergLookAndFeel` поверх `LookAndFeel_V4`**, а не с нуля: списки,
всплывающие меню и текстовые поля у V4 уже нарисованы прилично. Своими стали три вещи,
которые в стандартном виде выдают демо из туториала, — ручка (дуга с указателем,
а не шайба с риской), галка (тумблер) и список. Один акцентный цвет на всё окно:
второй сразу порождает вопрос «а что он значит», и ответа нет.

**Ловушка, стоившая половины сессии: рамка текстового поля под ручкой.** Она рисуется
`Label` внутри слайдера, и цвет он берёт **у самого слайдера**, а не у LookAndFeel.
`setColour (Slider::textBoxOutlineColourId, ...)` на LookAndFeel до неё не доезжает —
ставить надо на каждом слайдере.


### Вердикт по снимкам, сессия 17

Пользователь смотрел четыре снимка из `~/Downloads/BERG-S16/`.

**Функция принята, оформление — нет.** Дословно: «функционал дизайна топчик, с этим
проблем нет», но «слишком обычно что ли, может как-то осовременнить, может придумаем
свою фичу в дизайне». То есть раскладка, гашение мёртвых ручек, смена подписей и лента
нот работают и переделке не подлежат — а внешний слой ничем не отличается от любого
тёмного плагина с одним акцентом. Палитра и акцент при этом не отвергнуты: претензия
не «цвет не тот», а «нет своего лица». Заведено как [#52](#52), в M4 не входит.

**Размер 672 x 766 признан нормальным.** Это и есть размер по умолчанию для [#29](#29);
масштаб разрешено крутить в обе стороны, но стартовать окно должно отсюда.

Три вопроса из четырёх — про полосы, ленту и подписи — остались без ответа, потому что
претензия оказалась не к ним. Считаем их принятыми молчанием и больше не спрашиваем.

---

## [27] Визуализация активных нот и хвостов
**Labels:** ui
**Milestone:** M4

### Описание
Главная проблема пользователя: «плагин не работает» — а на деле не доехал MIDI.
Нужен индикатор: приходит ли MIDI, какие ноты активны, сколько голосов звучит.
Это диагностический инструмент под видом красивой анимации, и он снимет большую часть
вопросов в поддержку.

### Критерии приёмки
- [x] Видно, что MIDI приходит, даже когда аудио молчит
- [x] Активные ноты и число занятых голосов отображаются в реальном времени
- [x] Обмен данными с аудиопотоком без локов (atomic или FIFO)
- [x] При отсутствии MIDI пользователю видна явная подсказка

### Закрыта в сессии 16

**Лента под шапкой отвечает на «плагин не работает?» без слов.** Слева лампа входа
и строка «MIDI in — N notes, last G5, ratio 1.498»; при отсутствии MIDI на её месте
оранжевая подсказка про порт. Справа восемь ячеек голосов и счётчик `4/8`. Под ними
клавиатура на пять октав от до под унисоном — привязка к унисону, а не к фиксированной
C2: Root Key двигает всю картину, и нота унисона обязана остаться на виду. Она же
подчёркнута акцентом, потому что октаву Root Key не показывает (та же ловушка, что
породила текстовую строку про унисон в сессии 11).

**Лампа мигает на приход ноты, и это не украшение.** Счётчик отвечает «MIDI приходил
когда-то», мигание — «приходит прямо сейчас». Это разные ответы, и различить их и есть
весь смысл задачи.

**Обмен — восемь пар атомиков, публикуются раз в блок последним делом `processBlock`.**
`voiceNote[8]` (-1 — слот свободен) и `voiceLevel[8]`. Восемь пар вместо одной структуры
под локом потому, что лока в `processBlock` нет и не будет; рассогласование на один кадр
в картинке не видно. Аллокаций ноль — проверено тем же счётчиком, что и весь остальной
аудиопоток.

**Уровень огибающей нужен не для красоты: он и есть хвост.** Нота отпущена, огибающая
ползёт вниз, а голос всё ещё занят — без уровня «четыре голоса заняты» выглядело бы
как залипание.

### Снимок окна в PNG вместо запуска хоста

Побочный, но важный итог сессии: у `ProcessorTest` появился режим `--shot`.

```
./build/ProcessorTest_artefacts/Release/ProcessorTest --shot editor.png [пресет] [silent]
```

Он собирает процессор, прогоняет через него аккорд, создаёт редактор, дёргает таймеры
и пишет `createComponentSnapshot` в PNG. Интерфейс иначе правится вслепую: увидеть его
можно только в хосте, а хост в эстафету промптов не помещается. Заодно это единственная
быстрая проверка, что редактор создаётся, отрисовывается и разрушается без падения.

Две ловушки, обе стоили по итерации:

1. **Таймер редактора в консольном приложении не срабатывает.** `callPendingTimersSynchronously`
   вызвала таймер ленты (30 Гц) и не вызвала таймер окна (15 Гц): очередь сообщений
   не крутится, и обратный отсчёт перестаёт уменьшаться раньше, чем настанет срок
   более медленного. Лечится не подбором задержки, а тем, что **`paint` читает состояние
   у процессора напрямую**, а поля `shown*` остались только детектором изменений
   для перерисовки. Так окно право и на первом кадре — до любого тика.
2. **В Follow нота доезжает через всю латентность движка** (ADR 0006). Девяти блоков
   по 512 сэмплов не хватало, снимок выходил с пустой клавиатурой и надписью «нет MIDI».
   Шестьдесят блоков — хватает.

---

## [28] Пресеты: фабричные и пользовательские
**Labels:** ui, architecture
**Milestone:** M4

### Описание
5–8 фабричных пресетов, покрывающих реальные сценарии: тихий подклад в припеве,
октавный слой, широкий воздушный хвост, ритмический стаккато-повтор.
Сохранение и загрузка пользовательских — в файлы, а не в состояние хоста.

### Половина сделана в сессии 15 вместе с [#48](#48)

Шесть фабричных пресетов заведены через штатный интерфейс программ JUCE — таблица
и разбор в [#48](#48). Осталось только пользовательские: сохранение в файлы.
Штатный интерфейс программ для них не годится, там список фиксирован.

### Критерии приёмки
- [x] Не менее 5 фабричных пресетов, каждый звучит осмысленно из коробки — шесть
- [ ] Пользовательские пресеты сохраняются и загружаются
- [~] Пресеты переносимы между macOS и Windows — фабричные это таблица в коде,
      переносить нечего; критерий про пользовательские
- [x] Смена пресета во время звучания не даёт щелчка — замер в [#48](#48)

---

## [29] Ресайз окна и поддержка DPI
**Labels:** ui
**Milestone:** M4

### Описание
`setResizable` с сохранением пропорций и запоминанием размера в состоянии.
Проверить на Retina и на Windows со 125% и 150% масштабом — там ломается чаще всего.

### Критерии приёмки
- [x] Окно масштабируется без искажений и артефактов
- [x] Размер запоминается в состоянии плагина
- [x] Проверено на Retina; Windows 125 % и 150 % — не проверено, машины нет (ниже)
- [x] Минимальный размер не ломает раскладку

### Закрыта в сессии 17

**Раскладка не пересчитывается — она масштабируется целиком.** Вся геометрия
по-прежнему считается в базовых 672 x 766, а ресайз кладёт на готовое
`AffineTransform::scale`. Сетка 5 x N по сигнальному пути осмысленного узкого
варианта не имеет: чтобы её пересобирать под ширину, пришлось бы заново решать,
какая полоса во сколько колонок ложится, то есть переделывать [#26](#26). Трансформ
даёт то же самое даром и вместе с кеглями — при пересчёте раскладки шрифты пришлось
бы подбирать отдельно, и на 0,75 они разъехались бы с ячейками.

Соотношение сторон закреплено (`setFixedAspectRatio`) по той же причине: окно другой
пропорции показывало бы раскладку растянутой, а не перестроенной.

**Слой обязателен, и это требование JUCE, а не вкус.** `AudioProcessorEditor::editorResized`
содержит ассерт `getTransform() == hostScaleTransform` и комментарий рядом: свой
трансформ на самом редакторе затирает масштаб DPI, который ставит хост. Поэтому
трансформ лежит на дочернем `Content`, а редактору остаются три строки в `resized`.

**Пределы: 0,75 и 1,5** (504 x 574 и 1008 x 1149). Снизу — подписи набраны 11,5 пункта,
и ниже 0,75 они превращаются в серую рябь. Сверху — 1149 точек уже выше ноутбучного
экрана. Оба края сняты снимком и просмотрены; на 0,75 читается всё, включая числа
под ручками.

**Ловушка, стоившая половины задачи: `setResizeLimits` двигает окно.** Внутри он зовёт
`setBoundsConstrained (getBounds())`, а границы в конструкторе ещё нулевые — окно
на миг становится минимальным, `resized` успевает записать 0,75 в `editorScale`
процессора, и прочитанный следом «сохранённый масштаб» оказывается только что
затёртым. Окно открывалось минимальным всегда, независимо от состояния. Лечится
порядком: сохранённое значение снимается **до** настройки ресайза.

**Масштаб хранится в состоянии плагина рядом с индексом пресета**, а не параметром
APVTS: размер окна не музыкальная величина, автоматизировать его нечем, и в списке
параметров хоста он был бы мусором. Границы проверяются и на загрузке — состояние
приходит из файла проекта, то есть извне, и ноль в этом поле означал бы окно нулевого
размера. Проект, сохранённый до сессии 17, поля не содержит и открывается в 1.0.
Замер стоит в `test_processor.cpp` рядом с проверкой пресетов.

**Retina проверена офлайн, и вот чем именно.** У `--shot` появилось слово `retina`:
снимок рисуется с плотностью 2, то есть та же точка раскладки ложится в четыре
пикселя. Если бы в оформлении что-то было растровым или считалось в целых пикселях,
здесь оно поехало бы, а на плотности 1 выглядело бы целым. Не поехало ничего: ручки,
лента и шрифты — вектор.

**Чего проверить негде, и это не галочка.** Windows при 125 % и 150 % не проверен:
машины с Windows в проекте нет, а масштаб DPI там приходит от хоста через
`AudioProcessorEditor::setScaleFactor`, то есть по другому пути, чем ресайз мышью.
Известно только то, что эти два трансформа складываются, а не спорят: хостовый лежит
на редакторе, свой — на слое под ним. Это рассуждение, а не замер, и оно остаётся
незакрытым до [#31](#31) (тест-матрица DAW), где Windows появляется первым пунктом.

**Побочная находка: лента рисовала первый кадр из пустого кэша.** Снимок на 0,75 два
раза из четырёх вышел с надписью «MIDI не доехал» поверх звучащего аккорда — поля
`shown*` держали значения, с которых начинались, а первый тик таймера ещё не случился.
В хосте это один кадр из тридцати и незаметно, в снимке кадр ровно один. Это та же
ловушка, что [#27](#27) нашла в редакторе, но лечится иначе: там `paint` читает
процессор напрямую, а здесь кэш держит гаснущие уровни хвостов, то есть он не только
детектор перерисовки. Поэтому снимок заполняется в конструкторе ленты. После правки
шесть снимков подряд совпали побайтово.

### Сессия 18: вердикт по снимкам краёв не получен

`s17-4-window-075.png` (504 x 574) и `s17-6-window-150.png` (1008 x 1149) просмотра
не дождались, вопрос задан второй раз. Пределы 0,75 и 1,5 остаются: они выбраны
по кеглю подписей снизу и по высоте ноутбучного экрана сверху, и оба края прочитаны
глазом внутри сессии 17. Сдвигать их без возражения не на чем.

### Сессия 19: вопрос снят — ответа нет в третий раз

Снимки краёв не просмотрены и в третий раз. **Вопрос снят**, пределы 0,75 и 1,5
остаются по тем же причинам. Вернуться, если в хосте прозвучит «мелко» или
«не влезает в экран» — живой хост скажет это точнее снимка.

---

## [30] Профилирование CPU и бюджет нагрузки
**Labels:** perf, test
**Milestone:** M5

### Описание
Замер под нагрузкой: 8 голосов, 48 кГц, буфер 128. Цель из `docs/ANALYSIS.md` §7 — меньше 5%
одного ядра M1. Найти горячие точки (скорее всего интерполяция и кроссфейд), оптимизировать
только то, что реально греется. Не оптимизировать вслепую.

### Критерии приёмки
- [x] Цифры замерены и записаны в README с указанием машины и настроек
- [x] Цель < 5% ядра достигнута (4,3 % HQ с компенсацией формант)
- [x] Профиль снят инструментом, а не на глаз (`--bench`, а не ощущение)
- [x] Оптимизации не сломали регрессионные тесты DSP — оптимизаций не понадобилось

### Бюджет назван в сессии 17

**Один экземпляр: 4,3 % ядра.** Худший случай — восемь транспонированных голосов,
HQ, компенсация формант включена, 48 кГц, блок 512. Без компенсации 3,2 %, на Fast
0,6 %. Машина — Apple M5, 10 ядер, macOS 26. Замер снят в сессии 17 на свободной
машине (load average 1,79) и совпал с числом сессии 13 до десятой доли процента.
Цель `ANALYSIS.md` §7 — меньше 5 % — достигнута с запасом.

**Бюджет проекта: шестнадцать экземпляров на HQ одновременно.** Это 69 % одного ядра
и 0,46 мс из 10,67 мс, которые дают блоку 512 сэмплов на 48 кГц. Треть срока оставлена
нарочно: аудиопоток обязан укладываться не в среднем, а в худшем блоке, а худший блок
приходит вместе с чужим плагином, дисковым чтением и переключением ядра. Число
на ядро, а не на проект: хост раскидывает экземпляры по потокам сам, и на десяти ядрах
M5 практический потолок ставит не плагин, а хост.

**Когда не помещается — переключить Quality в Fast.** Это семикратный запас
(0,6 % против 4,3 %) и один список в окне, а не перестройка проекта. Цена названа
и измерена: расстройка хвоста 9,2 цента в среднем против 4,1 у HQ
([test_pitch_shifter](../Source/DSP/test_pitch_shifter.cpp)). Второй рычаг — Voices:
стоимость линейна по числу транспонированных голосов, унисонный голос бесплатен
(компенсация формант включается только при `freqMultiplier != 1`, разбор в [#24](#24)).

**Оптимизировать нечего, и это тоже результат.** Задача просила найти горячие точки
и «не оптимизировать вслепую». Горячая точка одна и известна — библиотека питчинга,
и она стоит втрое меньше потолка. Трогать интерполяцию и кроссфейд ради 4,3 % значит
менять работающее на своё такое же, но непроверенное.

### Снимок голосов сессии 16 не стоит ничего — замером, а не рассуждением

Единственное изменение сессии 16 в аудиопотоке — шестнадцать relaxed-записей на блок
(снимок голосов для ленты, [#27](#27)). Собраны два бинарника из одного исходника,
разница только в теле `publishVoiceSnapshot`, и прогнаны **вперемежку**, по очереди,
восемь пар подряд. Чередование здесь и есть метод: машина была занята чужим рендером,
абсолютные числа скакали от 5,6 до 23,1 %, но обе сборки ловили один и тот же шум.

Медиана со снимком 19,3 %, без снимка 20,0 % — то есть сборка **без** снимка вышла
чуть дороже, чего не бывает. Значит, стоимость снимка лежит ниже шума и не измеряется.
4,3 % остаются в силе.

### Правило замера, и оно шире, чем казалось

Сессия 16 обожглась: `--bench` дал 4,5 %, а через двадцать минут от 5,6 до 10,3 %
на том же бинарнике, потому что рядом крутился чужой процесс. Отсюда правило:
**смотреть `uptime` до замера и не верить цифре при load average выше двойки.**

Сессия 17 попала в то же самое (чужой рендер, load average 13-19) и нашла, что
одного `uptime` мало. Очевидный обходной путь — мерить процессорное время процесса
вместо настенного — на Apple Silicon **не работает**: под нагрузкой планировщик
уводит процесс на энергоэффективные ядра, и на ту же работу уходит вдвое больше
процессорного времени. В шести прогонах подряд `user` держался 2,26-2,30 с, а потом
падал до 1,05-1,12 с — при неизменном коде.

Признак чистого замера поэтому такой: **load average ниже двойки и `real` примерно
равно `user`**. Второе ловит именно уход на медленные ядра, которого первое не видит.

**Замер дождался свободной машины, и это стоило сессии два часа.** Чужой рендер
(Remotion, пять headless Chrome, потом ffmpeg на 914 %) держал машину почти всю сессию.
Числа снимались скриптом, который ждал падения load average ниже двойки и только тогда
запускал `--bench`. Дождался: 4,3 % и 0,6 % при load average 1,79. Способ повторяем
и лучше, чем «померить и не поверить».

---

## [31] Тест-матрица DAW
**Labels:** daw-compat, test
**Milestone:** M5

### Описание
FL Studio (Windows и macOS) — приоритет. Плюс Logic (AU), Ableton Live, Reaper, Studio One.
Проверять: загрузку, MIDI-роутинг, автоматизацию, сохранение состояния, ресайз, PDC.
Результат — таблица в `docs/DAW_COMPAT.md` с честными отметками, включая «не проверено».

### Критерии приёмки
- [ ] FL Studio на обеих платформах проверен полностью — **нет**, Windows-машины нет
- [x] Таблица совместимости заполнена, непроверенное помечено как непроверенное
- [x] Найденные несовместимости заведены отдельными issue ([#54](#54))
- [ ] Автоматизация параметров работает как минимум в FL Studio и Reaper — **не проверено**

### Сделано в сессии 18: таблица есть, галочек в ней почти нет

Матрица живёт в [DAW_COMPAT.md](DAW_COMPAT.md). Девять строк, занята одна:
**FL Studio 20.8.3 на macOS, VST3.** Остальное помечено `?` с названной причиной,
и причина в восьми случаях из девяти одна — хоста нет на машине.

**Это и есть результат задачи, а не её провал.** Матрица из галочек, проставленных
по рассуждению, врёт уверенно и обнаруживается у пользователя. Три состояния вместо
двух («да» / «нет» / «не проверено, потому что...») — единственный способ не соврать.

**Что стоит за единственной занятой строкой.** Четыре клетки, и у каждой есть чем
подтвердить: список плагинов после симлинка (сессия 01), MIDI-роутинг по ожившему
счётчику (сессия 01), высота и прозрачность по рендеру из FL (сессия 11, [#19](#19)),
PDC по взаимной корреляции того же рендера — 0,00 мс, разброс нулевой.

**Три клетки в этой же строке пусты, и это важнее заполненных.** Автоматизация,
сохранение проекта и ресайз в хосте не проверены **нигде**. Про ресайз легко
обмануться: офлайн проверено масштабирование мышью и Retina ([#29](#29)), а масштаб
DPI приходит от хоста другим путём — `setScaleFactor`. То, что два трансформа
складываются, а не спорят, пока рассуждение.

**Строка FL Studio / AU почти пуста намеренно.** В сессии 01 наблюдалось ровно одно:
FL сканирует `~/Library/Audio/Plug-Ins/Components` сам и AU в списке показывает.
Загружался ли плагин в FL как AU дальше списка — неизвестно. Вопрос пользователю задан
дважды и пока без ответа, а клетка не рядовая: у AU чистый `pluginval`, у VST3 нет
([#54](#54)).

**Побочная находка, которая обесценила целую клетку: CI не запускалась с сессии 05.**
Локально накоплено **40 неотправленных коммитов**. Значит «Windows собирается»
верно для кода девятидневной давности, а не для нынешнего. Это единственная белая
клетка, которая закрывается без чужой машины — одним `git push`.

**Push сделан в сессии 23**, 46 коммитов. macOS в CI зелёная, Windows **собирается**,
но ProcessorTest там падает на стрессе анти-клика — разбор в [#34](#34) и [#25](#25). Клетка «Windows собирается»
теперь верна для нынешнего кода; «работает на Windows» — нет.

**Побочная находка про инструмент: `pluginval` и `auval` открывают окно плагина
на экране** и мешают работать, если запускать их в фоне чужой сессии. У pluginval
это снимается `--skip-gui-tests`; отрисовка при этом остаётся покрыта офлайн-снимком
`ProcessorTest --shot`, который окна не создаёт. Команда записана в
[DAW_COMPAT.md](DAW_COMPAT.md).

---

## [32] Документация: как подать MIDI в плагин в FL Studio
**Labels:** docs, daw-compat
**Milestone:** M5

### Описание
Барьер входа номер один. Пошаговая инструкция со скриншотами: MIDI Out, выбор порта,
настройка порта на плагине, типичные ошибки. Плюс раздел про MIDI Offset и рекомендованные
значения. Без этого документа половина пользователей решит, что плагин сломан.

### Критерии приёмки
- [ ] Инструкция проверена на чистой установке FL Studio — **нет**, чистой установки нет
- [ ] Есть скриншоты каждого шага — **частично**: окно плагина снято, окна FL нет (ниже)
- [x] Раздел «не работает?» с тремя самыми частыми причинами — их там восемь
- [ ] Посторонний человек проходит инструкцию без вопросов — **не проверено**

### Сделано в сессии 18: документ догнал плагин

[FL_STUDIO.md](FL_STUDIO.md) был написан в сессии 01 по отладочному табло и с тех пор
не трогался. Сверен с тем, чем плагин стал за семнадцать сессий.

**Появилось объяснение, почему роутинг вообще такой странный.** Аудио-эффект
с MIDI-входом — редкая комбинация, и из неё растёт весь документ: `NEEDS_MIDI_INPUT TRUE`
в CMake, без которого FL не покажет у слота MIDI-вход, и `kAudioUnitType_MusicEffect`
(`aumf`) вместо `aufx` в AU. Ноты приходят не оттуда, откуда звук, — сведение портов
и есть плата за это.

**Оранжевая строка процитирована дословно и поднята в шаг 3.** Она и есть диагноз,
а не украшение: `No MIDI input - set the same port in MIDI Out and in the wrapper`.
Горит — дальше по инструкции идти незачем.

**Исправлено число, которое врало.** В черновике стояло «в Follow плагин просит
скомпенсировать 90 мс». Замерено заново: **Fast — 120 мс, HQ — 180 мс**, и это
зависит от ручки Quality, которой в сессии 01 ещё не было. От частоты дискретизации
число не зависит — проверено на 44,1 / 48 / 96 кГц, оба движка держат окно
в миллисекундах. Прежние 90 мс относились к отдельному укороченному движку Follow,
который был заведён и отменён в тот же день ([ADR 0006](adr/0006-follow-mode.md),
раздел «Отмена»): на живом голосе он промахивался по высоте вчетверо сильнее длинного.
ADR правильные числа называет с сессии 11 — врали документ и запись в `PROGRESS.md`.

**Дописано то, чего в сессии 01 не существовало:** шесть пресетов с назначением
каждого, три строки состояния под заголовком и что каждая значит, гаснущие и меняющие
подпись ручки ([#26](#26)), лента нот со счётчиком голосов и клавиатурой ([#27](#27)),
пределы ресайза ([#29](#29)).

**Таблица «если не работает» выросла с пяти строк до восьми.** Добавлены три отказа,
про которые известно, что на них напарываются: ноты идут, а хвоста нет (в слот
не приходит аудио — плагин эффект, а не инструмент); хвост звучит в унисон; хвост
поёт октавой выше — последнее случилось живьём и читалось как «расслоение голоса»,
хотя в окне прямо написано `ratio 2.000`.

**Рекомендация по формату стала явной: бери AU.** FL сканирует Components сам,
симлинк не нужен, `pluginval` на строгости 10 чистый. У VST3 симлинк обязателен
и известное расхождение в восстановлении состояния ([#54](#54)).

**Скриншотов окон самого FL нет, и взяться им неоткуда.** Хост в эстафету коротких
сессий не помещается (CLAUDE.md). Снимки собственного окна делаются офлайн одной
командой — обе записаны в конце документа, включая то самое состояние с оранжевой
строкой (`--shot no-midi.png 0 silent`). Снимки FL остаются за пользователем.

---

## [33] Инсталляторы, подпись и нотаризация
**Labels:** build, release
**Milestone:** M5

### Описание
macOS: pkg с установкой VST3 и AU в правильные каталоги, подпись Developer ID, нотаризация.
Windows: инсталлятор или просто архив с инструкцией. Учесть: на машине разработки только
Command Line Tools — для подписи и нотаризации может понадобиться полный Xcode.

### Критерии приёмки
- [x] macOS pkg устанавливает оба формата в правильные каталоги — установкой «только
      для меня»; «для всех» в `/Library` не проверено, нужен пароль администратора
- [ ] Пакет подписан и нотаризован, Gatekeeper не ругается на чистой машине — **нет**:
      членства в Apple Developer Program нет; что видно без подписи — замерено (ниже)
- [ ] Windows-сборка устанавливается по инструкции — **не проверено**, машины нет;
      инструкция в [RELEASE.md](RELEASE.md) §6
- [x] Процесс релиза описан в `docs/RELEASE.md` пошагово — обе ветки

### Сделано в сессии 19: без подписи замерено всё, с подписью — ничего

**Развилка пройдена веткой «нет членства».** Ответа на вопрос о членстве не пришло,
а замер ответил за него: `security find-identity -v` — ноль сертификатов. Developer ID
выдаётся только при членстве, значит подписывать было нечем при любом ответе.

**Главный замер: скачанный плагин без подписи не загружается вовсе.** Инструмент —
`scripts/load-bundle.c`, грузит бандл в процесс тем же вызовом, что хост. На копии
с карантином, поставленным как браузером, VST3 и AU отказывают одинаково:
`library load disallowed by system policy`, в журнале `syspolicyd` —
`Code did not match any currently allowed policy`. Без карантина тот же бандл
грузится. Консольному процессу система окна не показала — отказ молчаливый.

**`spctl` не различает ничего, и это находка про инструмент.** Промпт предлагал
смотреть на `spctl -a -vvv` до и после карантина. Он отвечает `rejected` в обоих
случаях: ad-hoc-подпись Gatekeeper не принимает никогда, а карантин решает только
то, спросят ли его при загрузке. Различает состояния только сама загрузка.
`syspolicy_check distribution` называет причину прямо: `Notary Ticket Missing`, `Fatal`.

**pkg без подписи собран скриптом и поставлен без sudo** — `scripts/package-mac.sh`,
установка `-target CurrentUserHomeDirectory`. Три ловушки, каждая молчаливая,
разобраны в [RELEASE.md](RELEASE.md) §3: переносимые бандлы (Installer обновил бы
копию в `build/`), Rosetta без `hostArchitectures`, и одиннадцать `._*` в payload —
атрибут `com.apple.provenance`, который на macOS 26 не снимается ничем, но при
установке сливается обратно: на диске `._*` ноль.

**Карантин pkg на разложенные файлы не переходит.** pkg с карантином, поставленный
`installer`, даёт бандлы без атрибута — и они грузятся. Отсюда вывод RELEASE §4:
**zip без подписи выпускать нельзя, pkg без подписи — терпимо**, один обход
в System Settings.

**Промпт сессии 18 ошибся в одном, записываю почему.** «Подпись — последний шаг
сверху, а не часть упаковки» верно для pkg, но не для бандлов в нём: бандлы
подписываются **до** `pkgbuild`, иначе в pkg уедут ad-hoc-копии. Скрипт подписывает
между копированием и упаковкой, если заданы переменные — эта ветка не запускалась.

**Что не проверено и почему, по одной причине на пункт.** Окно, которое покажут
FL Studio и Installer.app: оба всплывают поверх работы пользователя и ждут клика —
то самое, на что была жалоба в сессии 18. Установка в `/Library`: нужен пароль.
Вся ветка подписи: нет членства.

**Решение за пользователем**, и оно денежное: $99 в год. Аргументы — RELEASE §4,
выводы. Без него релиз возможен только pkg-установщиком с обходом Gatekeeper.

---

## [34] Регрессионные тесты DSP
**Labels:** test
**Milestone:** M5

### Описание
Офлайн-рендер с фиксированным входом и фиксированным MIDI, сравнение с эталоном по допуску.
Ловит тихие поломки DSP при рефакторинге — тот класс багов, который иначе находится
через месяц и на чужом миксе. Без фреймворков: скрипт и сравнение.

### Критерии приёмки
- [ ] Тест запускается одной командой и в CI — одной командой да, он последний
      в обычном прогоне `ProcessorTest`; шаг в CI добавлен, но **не запускался**:
      коммиты не отправлены
- [x] Покрыты: чистый дилей, один голос с питчем, аккорд, feedback
- [x] Допуск сравнения обоснован, а не подогнан под текущий вывод — замер ниже
- [x] Падение теста внятно сообщает, что именно разошлось — где, насколько за
      допуском, и что: уровень, полярность или форма

### Сделано в сессии 19

**Где живёт.** `ProcessorTest --regress [update] [id=value ...]`. Тот же прогон стоит
последним в обычном `ProcessorTest`, так что отдельной команды помнить не надо.
Эталоны — `tests/regression/*.flac`, 24 бита, полмегабайта на все четыре.
`update` переписывает их — только когда звук изменён намеренно и услышан.

| Сценарий | Движок | Ноты | Петля | Длина |
|---|---|---|---|---|
| `delay` | Fast | 60, унисон | выключена | 1,2 с |
| `voice` | HQ | 67, +7 | выключена | 1,2 с |
| `chord` | Fast | 60 64 67 71 | выключена | 1,2 с |
| `feedback` | Fast | 72, +12 | 60 %, окраска по умолчанию | 2,4 с |

Вход — пила 220 Гц на 0,4 с, дальше тишина; нота встаёт на 700-й сэмпл, внутрь
блока; последний блок короче 512. Mix 50: сухой путь и кроссфейд тоже в эталоне.
Сравнение — окнами по 10 мс, ошибка относительно уровня эталона в том же окне,
допуск −60 dB; в тихих окнах — абсолютный пол −100 dBFS.

**Допуск — замер, а не подгонка. Три числа.**

1. **Рендер детерминирован.** Два `update` подряд на arm64 дают побайтово те же FLAC.
   Запас 43–57 dB при повторной сверке — это усечение эталона до 24 бит
   (0,58 LSB ≈ −143 dBFS против пола −100), а не шум.
2. **Дрейф между платформами.** x86_64-срез того же universal-бинарника под Rosetta:
   без FMA против arm64 с FMA — ближайшее к Windows с MSVC, что есть на машине.
   Три Fast-сценария дают тот же запас, что повтор на arm64, то есть их дрейф ниже
   усечения эталона. `voice` (HQ) — запас 19 dB, самый тонкий.
3. **Наименьшие поломки, которые тест обязан поймать.** Пробы — параметр хвостом
   команды, поверх всех сценариев:

| Проба | Первое расхождение | Что сказал тест |
|---|---|---|
| `outputGain=0.1` | −38,7 dB, все четыре | разошёлся уровень: +0.10 dB |
| `mix=49` | −34,0 dB, все четыре | разошёлся уровень: +0.17 dB |
| `delayTime=300.1` | от −51,4 до −12,5 dB, все четыре | разошлась форма |
| `diffusion=51` | −53,9 dB, только `feedback` | разошлась форма |
| `width=0` | −35,5 dB, только `chord` | разошлась форма |

Все пять красные: у каждой пробы не меньше 6 dB за допуском уже в первом окне
расхождения и больше 20 dB в худшем.

**Петля посчитана на Fast, и это исправление собственной ошибки.** Первая версия
держала `feedback` на HQ. Замер записал «−42 dB» дрейфа, и по нему этому сценарию
был поставлен допуск −30 dB. Но число было запасом до порога, а порог в тихих окнах
не относительный, а пол −100 dBFS. Перепроверка с −30 dB покраснела: в тихом хвосте,
на −55 dBFS, HQ-петля расходится между платформами на −29 dB, и чем тише, тем больше.
Относительный допуск на таком не держится никакой. Та же петля с той же окраской
на Fast под Rosetta даёт запас 43 dB — ровно как повтор на arm64. Петле движок
не нужен: feedback снимается до питч-стадии ([#21](#21)), а HQ покрыт сценарием `voice`.

**Подсказку «уехал тайминг» пришлось убрать, и это находка.** Первая версия искала
сдвиг, на котором расхождение пропадает. Ни одна проба её не вызвала, даже сдвиг
delay time: сухой идёт мимо дилея, и сдвинутый хвост под несдвинутым сухим — это
изменение формы, а не сдвиг выхода. Уехать целиком выход у этого плагина не может,
значит ветка не срабатывала бы никогда. Осталась подсказка по уровню — коэффициент
методом наименьших квадратов, если он один объясняет 99 % ошибки, — и её пробы
подтвердили.

**Чего не проверено.** Windows и MSVC: шаг в CI добавлен, но CI не запускалась
с сессии 05. Rosetta — ближайшее к MSVC, что есть на машине, но не MSVC. Самый
чувствительный к платформе сценарий — `voice` (HQ), запас 19 dB. Покраснеет на первом
прогоне только он — это, скорее всего, дрейф, а не поломка: смотреть «за допуском
на N dB» и записывать замер сюда до того, как трогать число.

**CI, сессия 23, первый прогон с сессии 05** (`657dbd4`, run 34751571248).
macOS зелёная целиком: сборка, ProcessorTest с регрессией, pluginval. **Windows красная
на ProcessorTest, но не на допуске:** плагин и тест собрались, тест проработал 29 с
и вышел с кодом 127, **не напечатав ни строки** — ни одного «совпадает с эталоном».
Для bash 127 — «команда не найдена», но полминуты работы говорят о падении процесса,
а stdout в канал буферизуется и при падении теряется. Поэтому в `main` поставлен
`setvbuf (stdout, nullptr, _IONBF, 0)`: следующий прогон покажет раздел, на котором
тест умирает. Про допуск MSVC пока не известно ничего.

**Второй прогон** (коммит сессии 23, run 34752232973) показал: 127 — это `abort()` из `CHECK`
под bash на Windows. Тест проходит все разделы до «Анти-клик» и падает на
`ratio < 8.0` — отношение 9,7 ([#25](#25), сессия 23). **До регрессионных рендеров
Windows не доходит**, так что про допуск MSVC всё ещё неизвестно ничего. Файл лицензий
в Windows-бандле ([#42](#42)) не проверен по той же причине: артефакты не выгрузились.
macOS в этом прогоне тоже красная, но на pluginval — `Tempo Sync` ([#54](#54)).

---

## [35] Absolute / Harmonizer режим с детекцией питча
**Labels:** dsp, post-mvp
**Milestone:** Post-MVP

### Описание
YIN или pYIN на входе, `ratio = f_target / f_source`. MIDI задаёт абсолютную высоту
независимо от того, что поёт вокалист. Настоящий харморайзер. Нужны: обработка unvoiced,
гистерезис на скачках детектора, поведение при отсутствии питча.

### Критерии приёмки
- [ ] Детектор питча работает на вокале в диапазоне 80–1000 Гц
- [ ] Unvoiced-участки не дают случайных скачков высоты
- [ ] Переключение Relative/Absolute не роняет звучащие голоса
- [ ] Дополнительная латентность известна и спрятана в delay time

**После сессии 11 задача из «приятно бы» стала главной претензией к продукту.**
На живом прогоне в FL Studio пользователь услышал в Follow «расслоение голоса»
и принял это за микрозадержку. Запись экрана показала другое: в окне стояло
`last C6  ratio 2.000`. Мелодия была нарисована октавой выше унисона, и хвост пел
на октаву вверх. Ошибиться было легко и это не вина пользователя — **MIDI-нота
у нас значит не высоту, а величину транспонирования** от Root Key, и человек,
рисующий мелодию в пиано-ролле, ожидает ровно обратного.

Смягчено в сессии 11 строкой в окне («Unison (ratio 1.000) at C5»), но это подпорка.
Настоящее решение — эта задача: детектор даёт реальную высоту вокала, и MIDI-нота
начинает значить то, что все от неё и ждут, — абсолютную высоту подпевки.

**Третье подтверждение, сессия 13.** Пользователь, слушая рендеры, трижды описал
желаемый эффект через абсолютную высоту, ни разу не через транспонирование: «эхо
повторяло ноты плака и они были гармоничны», «оно ложится на рисунок мелодии»,
«их звучание в унисон мелодии». Ни одна из формулировок не выполнима относительным
режимом: MIDI-нота у нас значит сдвиг от Root Key, и эхо наследует высоту голоса.

Заодно вскрылось второе: **на речи задача не проверяется в принципе.** У дикторской
записи нет определённой высоты, интонация ползёт по фразе, и «лечь в унисон» там
нечему. Материалом для этой задачи может быть только поющий вокал.

**Вывод для плана:** метка post-mvp у этой задачи расходится с тем, как пользователь
описывает собственный продукт. Решение о переносе — за ним, но по трём независимым
описаниям подряд это не «приятно бы», а то, ради чего плагин задуман.

**Появился режим Follow ([ADR 0006](adr/0006-follow-mode.md)),
и в нём хвост звучит одновременно с сухим. Без детектора ratio считается от Root Key
вслепую, то есть подпевка наследует интонацию певца и уползает вместе с ним — в дилее
это терялось за задержкой, в унисоне слышно сразу. Считывать из аудио всю партию
(последовательность нот, громкость) отдельной задачей не нужно: сыграть хвостом ту же
мелодию Follow уже умеет при ratio 1. Ценность именно в абсолютном режиме.

---

## [36] Встроенный пиано-ролл (обход MIDI-роутинга)
**Labels:** ui, post-mvp
**Milestone:** Post-MVP

### Описание
Мелодия рисуется прямо в плагине, синхронно с транспортом хоста. Полностью снимает барьер
MIDI-роутинга в FL Studio. Возможно, именно эта фича продаст плагин — см. `docs/ANALYSIS.md` §9.
Так делают Waves Harmony и Auto-Tune Harmony, и не случайно.

### Критерии приёмки
- [ ] Ноты рисуются, двигаются, удаляются, меняют длину и velocity
- [ ] Паттерн синхронен с транспортом хоста и лупится
- [ ] Паттерн сохраняется в состоянии плагина и в пресетах
- [ ] Внутренний и внешний MIDI можно использовать одновременно или переключать

---

## [37] Scale lock / диатоническая коррекция
**Labels:** dsp, post-mvp
**Milestone:** Post-MVP

### Описание
Выбор тональности и гаммы, ноты подтягиваются к ближайшей ступени. Позволяет работать
без точной мелодии: задал «терция вверх в C minor» — получил гармонию.

### Критерии приёмки
- [ ] Основные гаммы: major, natural/harmonic minor, пентатоники
- [ ] Ноты вне гаммы подтягиваются по задокументированному правилу
- [ ] Режим комбинируется с Relative и с Absolute
- [ ] Смена тональности на лету не роняет голоса

---

## [38] HQ pitch engine
**Labels:** dsp
**Milestone:** M2 (вытащена из Post-MVP в сессии 08)

### Описание
Второй движок за интерфейсом `PitchShifter`: phase vocoder с phase locking, либо
Signalsmith Stretch, либо Rubber Band — по итогам лицензионной проверки из #6.
Латентность прячется в delay time, так что можно позволить себе большое окно.

**Поднята в M2 по замеру сессии 08.** Varispeed расстраивает хвост на 6–12 центов
в среднем и до 47 в худшей точке, и внутри алгоритма это неустранимо — см.
[ADR 0004](adr/0004-varispeed-window.md). Кандидат — Signalsmith Stretch (MIT).

### Критерии приёмки
- [x] Переключатель Quality: Fast / HQ работает без перезагрузки плагина
- [x] HQ слышимо чище на сдвигах больше октавы
- [x] Латентность HQ учтена в компенсации из #17
- [x] Лицензионные обязательства выполнены и записаны

**Сделано в сессии 09.** Движок — Signalsmith Stretch, вендорен копией в
`libs/signalsmith-stretch`. Расстройка упала с 9,2 цента средних (46,2 худших)
до 3,2 (11,0), цена — латентность 180 мс вместо 120 и 10 % ядра на восемь голосов
вместо 0,8 %. Решение и все замеры — [ADR 0005](adr/0005-hq-pitch-engine.md).
Тексты лицензий в бинарной поставке — #42.

---

## [39] Formant preservation
**Labels:** dsp, post-mvp
**Milestone:** Post-MVP

### Описание
Сохранение формант при транспонировании — убирает эффект «бурундука» на больших сдвигах вверх.
Спектральная огибающая через кепстральное лифтерирование или LPC, с раздельным сдвигом
источника и фильтра.

### Критерии приёмки
- [ ] Сдвиг +12 полутонов сохраняет узнаваемый тембр голоса
- [ ] Параметр Formant позволяет и намеренно смещать форманты
- [ ] Стоимость по CPU измерена и приемлема
- [ ] Работает совместно с обоими движками питчинга

---

## [40] MPE и per-note expression
**Labels:** midi, post-mvp
**Milestone:** Post-MVP

### Описание
Per-note pitch bend, pressure, timbre. Каждый голос получает собственные модуляции.
Открывает выразительную игру с MPE-контроллеров.

### Критерии приёмки
- [ ] MPE-сообщения разбираются, голоса реагируют независимо
- [ ] Pitch bend на голос работает плавно, без зиппера
- [ ] Обычный MIDI продолжает работать без изменений
- [ ] Проверено с реальным MPE-контроллером или эмулятором

---

## [41] Лицензирование: триал, ключи, защита от копирования
**Labels:** release, post-mvp
**Milestone:** Post-MVP

### Описание
Плагин платный ($10–25) с бесплатным триалом на 7 дней. По истечении триала без
валидного ключа плагин глушит выход.

Трезвая рамка: бинарник живёт на машине пользователя, снять проверку дизассемблером
может кто угодно. Цель не «невозможно украсть», а «заплатить проще, чем искать кряк» —
ровно то, чем ограничиваются iZotope и Waves.

Схема без своего сервера:
- **Триал.** Дата первого запуска пишется в файл настроек и дублируется в системное
  хранилище (Keychain на macOS, реестр на Windows), привязка к machine ID — иначе
  триал сбрасывается переустановкой.
- **Ключ.** Файл, подписанный Ed25519: внутри email покупателя и machine ID,
  публичный ключ зашит в бинарник. Проверка офлайн, серверная инфраструктура не нужна.
- **Продажа.** Gumroad или Lemon Squeezy — деньги, письма и налоги на их стороне,
  ключ генерит их вебхук. Свой биллинг не писать.
- **Watermark.** Имя покупателя из ключа показывается в окне About. Против расшаривания
  это работает лучше криптографии: файл со своим именем никто не выкладывает.

Ветвление по лицензии должно жить **вне** `processBlock` — флаг читается атомарно,
проверка ключа и работа с файлами только в GUI-потоке.

### Критерии приёмки
- [ ] Первый запуск заводит триал, оставшиеся дни видны в окне плагина
- [ ] По истечении триала без ключа выход глушится, плагин не падает и не молчит незаметно
- [ ] Переустановка плагина триал не сбрасывает
- [ ] Валидный ключ снимает ограничение, невалидный отвергается с внятным сообщением
- [ ] Проверка лицензии не делает аллокаций и ветвлений в аудиопотоке
- [ ] Покупка через Gumroad/Lemon Squeezy сквозняком: оплата → письмо → ключ → работает
- [ ] Имя покупателя видно в About

---

## [42] About: тексты лицензий сторонних библиотек в поставке
**Labels:** release, legal
**Milestone:** M5

### Описание
Плагин линкует Signalsmith Stretch и signalsmith-linear, обе MIT. MIT требует
сохранить текст лицензии и копирайт «во всех копиях или существенных частях
программы» — в репозитории тексты лежат в `libs/signalsmith-stretch/`, но
бинарная поставка это отдельная копия, и в ней их пока нет.

То же касается JUCE: её условия описаны в [#3](ISSUES.md) и требуют своей строки.

Самое дешёвое исполнение — экран About в окне плагина со списком: библиотека,
копирайт, тип лицензии, полный текст под кнопкой или в файле рядом с бандлом.
Отдельного окна ради этого заводить не нужно, если к M4 появится About из #41.

### Условия JUCE — по первоисточнику, сессия 23

Описание выше ссылается на #3, но условий JUCE там нет: #3 — это CI. Первоисточники —
`libs/JUCE/LICENSE.md` и текст JUCE 9 EULA, скачанный с juce.com/legal/juce-9-licence
13.09.2026 и прочитанный поиском по словам, а не пересказом.

- **JUCE 9 — это AGPLv3 или JUCE 9 EULA.** Своей лицензии AGPL у репозитория нет,
  исходники не открываются — значит, EULA.
- **Тип лицензии — Starter:** бесплатно, годовой доход или финансирование до $20 000 (§1.2).
  Для частного лица считается весь доход от использования JUCE, включая донаты, спонсорство
  и рекламу (§1.2.1).
- **В поставке EULA не требует ничего:** ни заставки, ни строки «Made with JUCE», ни текста
  лицензии, ни окна About. Слов splash, attribution, credit в тексте нет; notice — только
  запрет удалять копирайты JUCE из самого фреймворка (§2.9). `JUCE_DISPLAY_SPLASH_SCREEN=0`
  из `CMakeLists.txt` удалён: JUCE 9 его игнорирует и сама предупреждает об этом при сборке
  (`juce_gui_basics.cpp`). Строка JUCE в файле лицензий положена
  добровольно — рядом с чужими текстами её отсутствие выглядело бы странно.
- **Что важно на будущее, в STRATEGY это не записано:**
  - §1.14 — перешёл за $20 000, и нужен Indie ($40 в месяц или $800 разово) либо прекращение
    распространения;
  - §1.13 — **нельзя одновременно держать Starter и Indie/Pro и объединять продукты,
    сделанные под разными типами.** Платный второй плагин, который окупится, переведёт
    на Indie всё, включая этот.
- **Чужой код внутри JUCE тоже попадает в бинарник, и у него свои условия.** BSD-3 (FLAC,
  Ogg/Vorbis) требует копирайт «в документации или других материалах поставки», IJG —
  фразу про Independent JPEG Group, Apache-2.0 (SheenBidi, AudioUnitSDK) — текст лицензии.
  Их список — в `libs/JUCE/JUCE.spdx.json`; какие собираются — по зависимостям модулей
  `juce_audio_utils`, что в бинарнике — по строкам `strings` (libpng, zlib, HarfBuzz,
  LunaSVG, VST3 SDK или AudioUnitSDK есть; FLAC и Ogg на macOS выброшены линкером).

### Сделано в сессии 23: файл в обоих бандлах

`THIRD-PARTY-NOTICES.txt` в `Contents/Resources/` у VST3 и AU, 61 КБ, четырнадцать разделов:
Signalsmith Stretch и Linear, JUCE, zlib, HarfBuzz, SheenBidi, LunaSVG, PlutoVG, libpng,
libjpeg, FLAC, Ogg/Vorbis, VST3 SDK, AudioUnitSDK. Окна в плагине нет: MIT и BSD требуют
текст «в копиях» и «в материалах поставки», файл внутри бандла это выполняет буквально.

- **Собирает CMake, тексты — из самих зависимостей.** Пропал файл лицензии — конфигурация
  падает; изменился — переконфигурация сама (`CMAKE_CONFIGURE_DEPENDS`). Список компонентов
  привязан к версии JUCE из SPDX: другая версия — конфигурация падает с просьбой сверить.
- **Подпись.** Бандл подписывает JUCE после линковки. На чистой сборке порядок верный,
  но при изменении одного файла линковки не было — и `codesign --verify --strict` отвечал
  `a sealed resource is missing or invalid`. Лечит `LINK_DEPENDS` на файл: проверено
  временной правкой текста лицензии — перелинковка, переподпись, `--strict` зелёный.
- **Windows:** `MACOSX_PACKAGE_LOCATION` там не работает, файл копируется в
  `MIDI Delay.vst3/Contents/Resources/` шагом после сборки. Проверяется только в CI.
- **pkg:** файл в обоих бандлах из `scripts/package-mac.sh`, `--strict` зелёный у обоих.

### Критерии приёмки
- [x] Тексты лицензий Signalsmith Stretch и signalsmith-linear доступны из готового плагина
- [x] Условия JUCE выполнены и записаны
- [x] Список обновляется вместе с зависимостями, а не переписывается по памяти

---

## [43] Time Mode: Follow — хвост звучит одновременно с сухим
**Labels:** dsp, midi
**Milestone:** M2

### Описание
Заведена по итогам прослушивания в сессии 11. В режиме Free хвост стартует на ноте,
но поёт то, что звучало delay time назад: сухой вокал поёт один слог, хвост — предыдущий.
Как дилей это правильно, как «дилей повторяет мелодию» — нет. Нужен режим, где хвост
звучит в тот же момент и повторяет мелодию нота в ноту, то есть `delayTime = 0`.

Цена — латентность питчера, которую при нуле негде спрятать: она уходит в репорт хосту.
Полный разбор и замеры окна — [ADR 0006](adr/0006-follow-mode.md).

### Критерии приёмки
- [x] Параметр Time Mode есть в UI и в автоматизации
- [x] В Follow сухой и хвост приходят на один и тот же сэмпл, и на это есть тест
- [x] Латентность режима репортится хосту и видна в окне плагина
- [x] Движок Follow выбран по замеру расстройки, а не на глаз
- [x] В FL Studio компенсация работает, хвост садится на сухой

**Проверено в FL Studio 20.8.3** 9 сентября 2026. Ощущение «расслоения голоса»
в Follow оказалось не таймингом: запись экрана показала `ratio 2.000`, то есть
мелодия была нарисована октавой выше унисона и хвост пел на октаву вверх.
Компенсация в FL работает. Разбор — в [#35](#35).

**Осталось:** Tempo Sync встанет третьим пунктом в этот же параметр задачей [#20](#20).

---

## [44] Саунд-дизайн хвоста: насыщение и модуляция
**Labels:** dsp, sound
**Milestone:** M3

### Описание
Заведена по итогам прослушивания в сессии 11: «не хватает обработки, суховато».
Стерео-раскидка ([#23](#23)) и фильтры ([#22](#22)) закрывают часть, но не всю:
хвост остаётся чистой копией входа, а у дилеев, которые хочется оставить в миксе,
каждый круг чем-то окрашен. Кандидаты по возрастанию цены: мягкое насыщение в петле,
лёгкая расстройка/хорус на голос, диффузия (короткие аллпассы) перед выходом.

Порядок и объём — по слуху, а не списком: делать всё сразу нельзя, каждая добавка
меняет то, как звучат предыдущие.

Диффузия, модуляция и ducking выделены в [#45](#45), [#46](#46) и [#47](#47) —
там у каждой своя ловушка, и в одной задаче они не помещаются. Здесь остаётся
насыщение: мягкое ограничение в петле, которое красит каждый круг.

### Сделано в сессии 15: ограничитель, а не ручка Drive

Мягкое ограничение стоит **на одном лишь отводе обратной связи**, до сложения с сухим.
Это единственное верное место: на сумме оно красило бы и первый проход тоже, а критерий
задачи требует положения органов, при котором хвост бит-в-бит чистый. На feedback 0 отвод
равен нулю ровно, и ограничитель не делает ничего вообще.

Колено 0,7, потолок 1,0, склейка гладкая и по значению, и по наклону — на колене
производная ровно единица, излома нет. Обычный хвост порога не достаёт: уровень круга
при feedback 95 % около 0,33 (замер [#21](#21)).

Замер — отношение уровней выхода на двух амплитудах входа, 0,15 и 0,9. У линейной системы
оно равно отношению амплитуд, то есть 6,00:

| | feedback 0 % | feedback 95 % |
|---|---|---|
| с ограничителем | 6,00 | 1,91 |
| без ограничителя | 6,00 | 6,00 |

Первая строка и есть содержание задачи: без обратной связи плагин линеен до последнего
разряда, с обратной связью петля упирается в потолок. Вторая строка — контроль: если
ограничитель однажды отключат, замер это увидит. Уровень хвоста на горячем входе — 1,49
при расчётной границе 1,9 (сухой 0,9 плюс потолок отвода 1,0).

**Ручки Drive нарочно нет.** Замер сессии 14 показал, что петля на 95 % идёт вниз,
а не вразнос: значит это не защита от разгона, а потолок на горячем материале, и объяснять
пользователю ручке было бы нечего. Пятнадцать почти одинаковых ручек в окне и так не
объясняют себя ([#26](#26)). Если по слуху окажется, что нужен характер, а не потолок, —
Drive заводится как параметр, колено едет вниз, и это отдельное решение.

### Критерии приёмки
- [x] Насыщение в петле обратной связи не разгоняет уровень при feedback 95 %
- [x] Модуляция не слышна как расстройка на длинных хвостах — закрыто в [#46](#46)
- [x] Есть положение всех органов, при котором хвост бит-в-бит чистый: feedback 0
- [~] Каждая добавка оценена на слух отдельно от остальных — насыщение на слух ещё
      не оценивалось: на рендерах сессии 15 оно не включается, там уровни ниже колена

---

## [45] Диффузия хвоста: алл-пассы в петле
**Labels:** dsp, sound
**Milestone:** M3

### Описание
Заведена в сессии 11 по запросу «хочу, чтобы сам дилей был качественный, как у Valhalla».
Из четырёх вещей, которые отличают дорогой дилей от простого, эта даёт больше всех
на единицу работы: цепочка алл-пассов в петле обратной связи размывает дискретные
повторы в связный хвост.

Ставить **в петлю обратной связи**, то есть на возврат перед записью в кольцо. Тогда
первый хвост остаётся чистым, а каждый следующий круг размывается сильнее — это и есть
поведение, которое слышно как глубина. Инвариант «feedback берётся до питч-стадии»
при этом не нарушается: диффузор стоит именно там.

Схема: 4 алл-пасса Шрёдера в серию, `y[n] = -g·x[n] + x[n-M] + g·y[n-M]`, длины M
взаимно простые в сэмплах (порядка 7, 11, 17, 23 мс), `g` от 0 до ~0,7 по ручке.
Разные длины на левый и правый канал дают ширину даром.

**Алл-пассы безопасны при feedback 95 %** — у них единичное усиление на всех частотах,
и петлю они не разгоняют. Этим они выгодно отличаются от резонансных фильтров (#22).

### Ловушка, из-за которой заведён отдельный абзац
При `g = 0` алл-пасс не исчезает, а вырождается в чистую задержку на M сэмплов.
То есть «Diffusion 0» молча удлинит петлю на сумму длин — около 58 мс — и интервал
повторов уедет. Либо обходить цепочку целиком на нуле, либо вычитать её задержку
из времени петли. Существующий тест на интервал второго повтора
(`test_processor.cpp`, раздел про нижний предел delay time) это поймает.

### Критерии приёмки
- [x] При Diffusion 0 выход бит-в-бит совпадает с текущим
- [x] Интервал повторов не зависит от положения Diffusion
- [x] При feedback 95 % уровень не разгоняется
- [x] Металлического призвука на плотной диффузии нет — проверено на слух
- [x] Проверено в обоих режимах Time Mode

### Сделано в сессии 12
`Source/DSP/Diffuser.h`, заголовочный и без зависимости от JUCE, как DelayBuffer.
Четыре звена Шрёдера в серию, `w[n] = x[n] + g*w[n-M]`, `y[n] = w[n-M] - g*w[n]`.
Длины 7/11/17/23 мс слева и 9/13/19/26 мс справа — ширина досталась даром. `g` едет
от 0 до 0,7 ручкой Diffusion (значение по умолчанию 50 %, выбрано на слух).

**Ловушка обойдена вычитанием, а не обходом цепочки.** Петля читает кольцо второй раз,
на `getDelaySamples` короче: алл-пасс при любом `g` несёт свои M сэмплов, и без вычета
интервал повторов уезжает. Замерено на снятом вычете: центр тяжести второго повтора
уходит на **+3011 сэмплов (+63 мс)** уже при Diffusion 25 %. С вычетом промах не больше
6 мс на всём ходе ручки.

**Цепочка крутится всегда, даже на нуле ручки, а подмешивается множителем.** Обход
цепочки на нуле дал бы холодный старт при включении (60 мс провала) и щелчок при
выключении; постоянно прогретая цепочка с плавным подмешиванием не даёт ни того,
ни другого, а на нуле ручки в петлю уходит ровно недиффузированный сигнал — бит-в-бит.
Цена — четыре умножения на канал на сэмпл впустую при Diffusion 0.

**Известный потолок:** если петля короче цепочки (это Follow на времени меньше 70 мс),
вычесть нечего, и интервал повторов упирается в длину цепочки. Помечено `ponytail:`
в `renderSegment`.

**Побочное наблюдение: хвост с диффузией живёт дольше, чем даёт оценка `feedback^n`.**
Алл-пасс добавляет петле фазу, то есть на части частот удлиняет её круг: при feedback 95 %
измеренное затухание идёт как 0,97 за круг вместо 0,95. Это не разгон (усиление петли
единичное, проверено тестом), но `getTailLengthSeconds` при плотной диффузии занижает
хвост примерно в полтора раза. На потолке 20 с это не видно, чинить нечего.

---

## [46] Модуляция времени: wow и flutter
**Labels:** dsp, sound
**Milestone:** M3

### Описание
Медленный случайный дрейф позиции чтения на доли миллисекунды. Расцепляет повторы
между собой и убирает металлический призвук, который вылезает на высоком feedback,
когда все круги идеально совпадают по фазе. Кольцо уже читает дробную позицию
с интерполяцией Catmull-Rom (#8), так что механика есть — нужен только генератор.

Ориентир: 0,1–3 Гц, глубина 0,1–5 мс. Больше — это уже эффект, а не характер.

### Развилка, которую надо решить явно
Модулировать позицию чтения **петли обратной связи** — классический ленточный
характер, дрейф накапливается по кругам. Модулировать позицию чтения **голосов** —
дрожание попадёт на вход питчера, и Signalsmith честно его воспроизведёт. Второе
может оказаться и лишним, и красивым; решать на слух, а не по аналогии.

### Критерии приёмки
- [x] При глубине 0 выход бит-в-бит совпадает с текущим
- [x] На feedback 90 % металлический призвук слышимо слабее, чем без модуляции
- [x] Модуляция не читается как расстройка на длинных хвостах
- [x] Решение по развилке записано с обоснованием

### Сделано в сессии 13

**Развилка решена в пользу петли, и вот почему.** Дрожание, поданное на вход питчера,
фазовый вокодер воспроизвёл бы честно — то есть оно стало бы уходом высоты, а критерий
задачи требует ровно обратного. В петле же дрейф расцепляет круги между собой,
накапливается от повтора к повтору и высоты первого хвоста не трогает вовсе.

**Следствие, которое стоит знать:** при feedback 0 модуляция не слышна совсем — она живёт
на возврате обратной связи, а первый хвост идёт из голоса. Это ровно то, чего задача
и просила («расцепляет повторы между собой»), но на слэпбэке без обратной связи ручка
Modulation не делает ничего, и это не поломка.

**Генератор — сумма двух синусов** на 0,23 и 0,37 Гц, веса 0,6 и 0,4. Частоты
несоизмеримые: у суммы нет общего периода, и дрейф не читается как ровное качание.
Глубина на полной ручке 4 мс, по умолчанию 20 %.

**Смещение только в плюс.** Знакопеременное на минимальном delay time упиралось бы
в нижний предел кольца, и дрейф стал бы односторонним сам — молча и только на коротких
временах. Цена честного варианта: постоянная составляющая в полглубины, до 2 мс.

**Замерено, а не оценено на слух.** Металлика петли — это её резонансы, и она выражается
числом: тон ровно на резонансе (1 кГц при петле 200 мс), feedback 90 %. Без модуляции
круги складываются в фазе и уровень 1,59; с полной модуляцией — 0,30, то есть впятеро
меньше. Уход высоты в хвосте (он же «читается как расстройка»): на значениях
по умолчанию 3,5 цента, на полной ручке и feedback 90 % — 40 центов. Второе — сознательно
крайнее положение обеих ручек. При глубине 0 разброс ровно нулевой, и это то же
доказательство бит-в-бит, что точное число в отклике петли.

**Та же схема обхода, что у диффузора:** генераторы крутятся всегда, подмешиваются
глубиной. На нуле ручки позиция чтения ровно прежняя, включение не даёт скачка.

---

## [47] Ducking: хвост приседает под сухим
**Labels:** dsp, sound
**Milestone:** M3

### Описание
Детектор огибающей на сухом входе, его выход приглушает wet. Хвост не спорит с вокалом
за место в миксе, а проявляется в паузах. Дёшево и сильно влияет на то, садится ли
подклад в микс — а это ровно критерий готовности вехи M3.

Ориентир: атака 5–20 мс, спад 100–500 мс, глубина до -12 dB.

### Критерии приёмки
- [x] При глубине 0 выход бит-в-бит совпадает с текущим
- [x] Хвост проявляется в паузах и уходит под сухим
- [ ] Приседание не слышно как накачка на плотном материале
- [x] Работает одинаково в обоих режимах Time Mode

### Сделано в сессии 13

**Детектор снимает сухой после линии задержки, а не до неё** — расхождение с промптом
сессии, и оно намеренное. Довод промпта был в том, что в Follow сухой придерживается
на латентность питчера и детектор, снятый после линии, опоздает. На деле наоборот:
в Follow **весь** плагин опаздывает от своего входа на выравнивание — и сухой, и хвост.
Детектор на сыром входе присел бы на 180 мс раньше сухого, то есть до того, как слог
прозвучал. Взятый после линии, он совпадает с сухим в обоих режимах, а это и есть
критерий задачи. Замер подтверждает: приседание 0,306 от исходного уровня в Free
и 0,306 в Follow — цифра в цифру.

**Без порога и без knee.** Полное приседание наступает на -12 dBFS сухого (множитель
чувствительности 4), глубина на полной ручке -12 dB. Атака 10 мс, спад 250 мс — константы,
не ручки: две лишние ручки в окне стоят дороже, чем разница между 200 и 300 мс.

**По умолчанию 50 %,** и это тоже слуховое решение: рендеры с приседанием и без
пользователь описал как «каша в обоих, но с приседанием лучше». Довод против (молча
жать хвост у того, кто открыл плагин впервые, — значит соврать про то, как эффект
звучит) проиграл простому факту: на голосе с частыми повторами хвост без приседания
дерётся с сухим за одно и то же место.

Замер: под сухим уровень хвоста 1,59 -> 0,49 (-10,3 dB), в паузе 1,32 -> 1,18, то есть
хвост возвращается. Два разных числа, а не одно: детектор обязан отпускать, иначе
приседание было бы просто тише сделанным wet.

---

## [48] Громкие пресеты: доказать, что эффект слышно
**Labels:** ui, docs
**Milestone:** M4

### Описание
Плагин спроектирован под «еле заметный слой в миксе» ([ANALYSIS.md](ANALYSIS.md) §1),
и это делает его непродемонстрируемым: демо-видео «послушайте, как почти ничего
не изменилось» не существует. Разбор — [STRATEGY.md](STRATEGY.md) §3 и §5.

Движок менять не надо, надо показать, что он умеет громкое. Четыре опорных пресета
с настройками из STRATEGY.md §5: Chord Pad, Arp Echo, Octave Drop, Ghost Choir.
Пресетом по умолчанию открывается Chord Pad, а не текущий тихий подклад.

**Ручная проверка идёт первой и до кода.** Полчаса в FL Studio: выставить настройки
Chord Pad и Arp Echo руками, записать 15 секунд «сухой вокал → эффект». Если у автора
не возникает «о, что это» — вопрос не в пресетах, и дальше по [STRATEGY.md](STRATEGY.md) §10.

**Ожидаемый побочный эффект.** На Mix 70% станет слышно то, что незаметно на 25%:
щелчки на границах голосов, металлика питчера, гребёнка от кроссфейда. Это не повод
делать пресеты тише — это работа вехи M3 (#45, #22, #46, #47), и она должна быть
закончена до пресетов.

### Первый попавший набор настроек найден в сессии 13, ухом

Пользователь послушал рендер на своём материале (`lines_140_bpm_-_bm_-_d`) и сказал:
«вообще топчик, вроде то, что я и задумывал изначально». Это первое попадание за всю
работу, и настройки стоит сохранить дословно — они и есть заготовка пресета:

| | Распевный вокал (попал) | Плотная читка (кашу дал) |
|---|---|---|
| Темп материала | 140 BPM, си минор | ~129 BPM (замер, слабый) |
| Ноты | арпеджио Bm7: B D F# D A F# D B | те же дали кашу |
| Шаг нот | четверть, 428,6 мс | нужна половинная и реже |
| Delay Time | полтакта, 857 мс | нужен целый такт |
| Mix | 40 % | 22-28 % |
| Feedback | 15 % | 0, один повтор |
| Ducking | 50 % | 75-85 % |
| Ping-pong | вкл, Width 150 % | вкл |

**Материал диктует настройки сильнее, чем вкус.** Тот же набор, перенесённый с распевного
вокала на рэп-читку, превратился в кашу: слоги идут вчетверо чаще, а эхо приходило
с прежним интервалом и накладывалось само на себя. Значит четырёх пресетов «по звуку»
(Chord Pad, Arp Echo, Octave Drop, Ghost Choir) мало — нужен хотя бы один разрез
«по материалу»: распевное против плотного. Это же объясняет, почему все рендеры
до сессии 13 звучали неубедительно: настройки были одни, а материал каждый раз разный.

### Вердикт по трём диагностическим рендерам читки (сессия 14)

Три рендера сессии 13 выслушаны. Порядок от чистого к мутному:

1. **`rap-1-unison`** — эхо без транспонирования, самый чистый
2. **`rap-3-down`** — эхо октавой вниз
3. **`rap-2-fast`** — движок Fast, самый мутный

Дословно: «унисон лучший, октава вниз на 2 месте, фаст на последнем, но в целом все норм
показались вроде».

**Это разворачивает главную гипотезу сессии 13.** Она гласила: каша от того, что окно
анализа HQ (180 мс) длиннее слога быстрой читки (шестнадцатая при 140 BPM — 107 мс),
и Fast с коротким окном должен выиграть. Fast оказался последним. Значит размер окна
ни при чём, и разговор про третий движок или окно поменьше не нужен — ADR 0005 остаётся
как есть.

**Что остаётся объяснением.** Первое: транспонирование само по себе стоит разборчивости
на плотном материале — унисон чище всех. Второе: то, что не спорит с оригиналом за ту же
полосу, читается лучше — октава вниз на втором месте. Третье, и оно же довод за #20:
Fast расстраивает и **гуляет по тайму** (ADR 0004), а на плотной читке тайминг критичнее
тембра. Проиграл именно тот вариант, у которого хвост не стоит на месте.

**И четвёртое, важное для #48: «в целом все норм».** То есть каша сессии 13 была не
свойством материала, а свойством настроек — прежние (эхо через полтакта, ноты из чужой
тональности, mix 40 %) на читке не работают, а разреженные и тихие работают. Разрез
пресетов «по материалу» подтверждён.

**И главное: ноты обязаны быть из тональности материала.** До сессии 13 паттерн в рендере
был зашит в до-мажоре, и на любом другом материале плагин играл мимо тональности.
«Негармонично» было виной стенда, а не плагина.

### Вердикт по трём рендерам сессии 14 и что он закрыл

Пользователь послушал `~/Downloads/BERG-S14/` и сказал дословно: **«сетка работает,
оба варианта читки чёткие»**. Это закрывает сразу два открытых вопроса.

Первый: `s14-1-vocal-sync` — сетка слышна, хвост встаёт в такт. Претензия сессии 13
«поёт не в такт» была про отсутствие tempo sync, а не про питчер, и #20 её сняла.

Второй: `s14-2-rap-grid-unison` и `s14-3-rap-grid-down` — оба чёткие, разницы между
унисоном и октавой вниз пользователь не выделил. Каша сессии 13 была свойством настроек
(эхо через полтакта, mix 40 %), а не материала: разреженная сетка её вылечила.
**Разрез пресетов «по материалу» подтверждён вторично и стал кодом.**

### Сделано в сессии 15

Шесть фабричных пресетов через штатный интерфейс программ JUCE (`getNumPrograms`,
`setCurrentProgram`) — то есть они видны и в меню пресетов хоста, и в списке в шапке окна.
Таблица — в начале `Source/PluginProcessor.cpp`.

| Пресет | Что задаёт | Откуда числа |
|---|---|---|
| Chord Pad (по умолчанию) | Follow, Mix 70, Attack 60, Release 800, Voices 8, FB 0 | STRATEGY §5 |
| Arp Echo | Free, Sync 1/8., FB 45, Voices 8, Attack 1, Mix 30 | STRATEGY §5 + слух, см. вердикт |
| Octave Drop | Root Key B, Pitch Range 24, Mix 60, Low Cut выкл | STRATEGY §5 |
| Ghost Choir | HQ, Width 100, Mix 45, Release 1500, High Cut 6 кГц | STRATEGY §5 |
| Sung Vocal | Sync 1/2, Mix 40, FB 15, Ducking 50, ping-pong, Width 150 | таблица выше, сессия 13 |
| Dense Rap | Sync 1/1, Mix 25, FB 0, Ducking 80, ping-pong, Width 100 | таблица выше, сессия 14 |

**Время задано делителем, а не миллисекундами.** Записанные в таблице выше 857 мс верны
ровно при 140 BPM; в пресете стоит `1/2`, и оно едет за темпом проекта. Проверяется тестом:
после любого пресета `delayTime` равен умолчанию, то есть ни один не трогает миллисекунды.

**Пресет — снимок целиком, а не набор поправок.** `applyPreset` сначала возвращает все
параметры к умолчаниям и только потом кладёт свои. Иначе Ghost Choir, выбранный после
Arp Echo, звучал бы не так, как на свежем экземпляре. Единственное исключение — Bypass:
обход это состояние пользователя, а не звука.

**Смена пресета на звучащем хвосте не щёлкает.** Замер: отношение выброса к 99,9-му
процентилю 1,9 при фоне 3,5 у общего стресс-теста. Chord Pad в переборе не участвует —
он единственный меняет Time Mode, а это объявленный разрыв (ADR 0006).

### Открытое: громкий пресет делает трек тише

Замер на материале `lines_140_bpm_-_bm_-_d` (15 с, первые 5 сухие, дальше пресет):

| Пресет | Разница уровня |
|---|---|
| Chord Pad | −6,0 dB |
| Arp Echo | −6,1 dB |
| Octave Drop | −6,5 dB |
| Ghost Choir | −5,1 dB |
| Sung Vocal | −5,1 dB |
| Dense Rap | −3,8 dB |

Причина не в пресетах, а в законе микса: `dry * (1 - mix) + wet * mix`. На Mix 70 сухой
падает на 10,5 dB, хвост возвращает 4,5, итог −6. Для задачи, которая называется
«доказать, что эффект слышно», это ровно та ошибка, которой она посвящена: включение
пресета читается как «стало тише», а не как «о, что это».

**Компенсировать Output Gain в пресетах намеренно не стал**, и вердикт это подтвердил:
+6 dB решают проблему на этом материале и клипуют на горячем, а на слух проблемы
не оказалось вовсе — см. раздел «Компенсация выхода не нужна» выше. Замер здесь
остаётся объяснением того, почему уровень падает, а не открытой задачей.

### Вердикт по шести рендерам сессии 15 — и главная поправка к STRATEGY §5

Пользователь послушал `~/Downloads/BERG-S15/`. Порядок от лучшего:

| | Пресет | Дословно |
|---|---|---|
| 1 | Ghost Choir | «самое годное» |
| 2 | Octave Drop | «тож норм, но в начале почему-то не было дилэя, а потом резко много началось, под конец стало норм» |
| 3 | Sung Vocal | «тож ничего» |
| 4 | Chord Pad | «чётко» |
| 5 | Dense Rap | «ну норм, не понял зачем такая долгая атака, но такое тоже делают иногда» |
| 6 | Arp Echo | «не так хорошо звучит, может потому что дилэй слишком громкий (обычно его делают еле заметным)» |

**«О, что это» получено — задача попала.** Пять пресетов из шести названы рабочими,
и это первый случай за всю работу, когда ни один рендер не назван шляпой.

**Главная поправка, и она шире одного пресета.** STRATEGY §5 требовала громкости
от всех четырёх опорных пресетов одинаково. Вердикт показал, что громкость работает
не везде: три верхних места заняли **гармонические слои** — хор, октава вниз,
распевное эхо в терцию, — а единственную претензию собрал **ритмическое эхо**.
Разница не во вкусе, а в том, чем эффект занят: гармонический слой добавляет
к материалу голос, которого в нём не было, и громкость делает его слышимым;
ритмическое эхо повторяет тот же голос в ту же долю такта, и громкость превращает
его в соперника, а не в слой. **Громко — то, что добавляет; тихо — то, что повторяет.**
Практическое следствие: Arp Echo получил Mix 30 вместо умолчания 50.

**Два замечания оказались не про пресеты.** «В начале не было дилэя» — это структура
демо: первые пять секунд плагин обойдён нарочно, чтобы слышать переход одним файлом.
«Долгая атака» у Dense Rap — не атака (там 10 мс, самая быстрая из шести), а целый такт
до первого повтора: пресет рассчитан на плотную читку, а рендер сделан на распевном
материале. Оба стоит держать в голове при следующих рендерах: **демо-структура
и несвойственный материал читаются как дефект пресета.**

### Компенсация выхода не нужна — вопрос закрыт

Открытый вопрос сессии 15 («громкий пресет делает трек тише на 5–6 dB, компенсировать ли
Output Gain») закрыт вердиктом, причём в обратную сторону: единственная претензия
к громкости была «слишком громко», а не «слишком тихо». Строку `outputGain` в пресеты
не добавлять; закон микса не трогать. Замер остаётся ниже как объяснение того,
почему уровень падает, а не как задача.

### Ручная проверка: что сделано офлайн вместо FL

Пользователь передал проверку офлайн-замерам. Пункт про живой playhead закрыт полностью,
пункт «услышать своими ушами» офлайн не закрывается по определению — остаются рендеры.

1. **Темп меняется на ходу — сетка едет за ним.** До сессии 15 темп подсовывался
   фиксированным на весь прогон, и «сетка едет за проектом» проверялось тем, что другой
   прогон даёт другое число. Теперь темп меняется между блоками, как это делает хост:
   1/4 при 120 BPM даёт хвост на 24000 сэмплах, при 150 — на 19200, при 90 — на 32000.
   Это ровно 500, 400 и 666,7 мс. Ручка Delay Time при этом не двигается: сетка меняет
   эффективное время, а не значение параметра.
2. **Непрерывный разгон темпа 90→160 при звучащем хвосте плюс смена делителя поверх.**
   Отношение выброса 8,1 против 7,8 у того же прогона на стоячем темпе — движение темпа
   не стоит ничего. Критерий тут относительный нарочно: абсолютный порог зависит
   от материала, и на одном тоне фон вчетверо ниже, чем у стресс-теста на двух.
3. **Значения по умолчанию.** При 120 BPM четверть — ровно 500 мс, то же число, что
   на ручке: включение Sync звук не двигает. Проверяется тестом.
4. **Пятнадцатисекундные рендеры «сухой → эффект»** — `~/Downloads/BERG-S15/`, по одному
   на каждый пресет, первые 5 секунд плагин обойдён. Ключи рендера: `preset=N`,
   `drySeconds=`, `seconds=`.

### Вердикт по перерендеренному Arp Echo, сессия 17

**По громкости вопрос закрыт: «по громкости норм».** Mix 30 остаётся, правка сессии 15
принята, спор о компенсации Output Gain не открывается заново.

Но вердикт пришёл не пустым: «дилэй не сразу начинает работать, а потом превращается
в кашу». Это две разные вещи, и только вторая — дефект.

**Первая половина — структура демо, а не пресет.** Первые пять секунд рендера плагин
обойдён нарочно (`drySeconds=`), чтобы переход «сухо → эффект» был слышен одним файлом.
Ровно это замечание уже приходило в сессии 15 и уже записано выше как **«демо-структура
читается как дефект пресета»**. Второй случай подряд — значит, дело не в слушателе,
а в файле: **рендеры, где начало обойдено, обязаны называть это в таблице `NEXT.md`
строкой про первые секунды, а не только ключом рендера.** Отдельного правила для этого
раньше не было, теперь есть.

**Вторая половина — настоящая, и заведена как [#53](#53).** Arp Echo стоит на 1/8.
(`division` 7) с `feedback` 45 и восемью голосами: точка каждые три восьмых, поверх
собственного хвоста, транспонированного в восемь высот. Каша здесь ожидаема
арифметически, и это первый пресет, где претензия к самому звуку хвоста, а не к его
уровню.

### Критерии приёмки
- [x] Ручной прогон сделан офлайн-замерами, результат записан выше; «слышно / не слышно»
      остаётся за рендерами `~/Downloads/BERG-S15/`
- [x] Пресеты сохраняются, загружаются и переживают перезагрузку проекта
- [x] Пресет по умолчанию — Chord Pad
- [x] Смена пресета на звучащем хвосте не щёлкает (замер выше)
- [x] Есть 15-секундный рендер «сухой вокал → эффект», пригодный для видео

---

## [49] Имя разработчика, сайт и подписка
**Labels:** release, docs
**Milestone:** M5

### Описание
Решение выпускать MIDI Delay бесплатно ради узнаваемости — [STRATEGY.md](STRATEGY.md) §6.
Для этого нужен минимальный набор, без которого релиз некуда вести.

Имя разработчика отдельно от имени плагина: «MIDI Delay» — это продукт, под именем
разработчика выйдет и второй, и пятый. Проверить, что имя не занято на KVR и в App Store,
и что домен свободен.

Страница: что делает, скриншот, видео, кнопки скачивания под macOS и Windows, форма
подписки. **Скачивание без обязательной регистрации** — жёсткий gate режет и скачивания,
и охват, подписка предлагается, но не требуется.

Плюс короткий FAQ и честная строка про поддерживаемые хосты и платформы: у бесплатного
плагина поддержка есть, а выручки нет, и объём переписки ограничивается заранее.

### Сессия 23: имя — Berg, занятость проверена

Ответ пользователя: **«Berg остаётся»**. Идентификаторы не трогались: `COMPANY_NAME "Berg"`,
код производителя `Berg`, `com.Berg.MidiDelay`, `com.Berg.MidiDelay.pkg`.

| Где | Что нашлось | Чем |
|---|---|---|
| KVR | Разработчика Berg нет: `kvraudio.com/developer/berg` и `/berg-audio` отдают общий каталог. Рядом только Steinberg и «Drumforge Bergstrand» — продукт, не разработчик | поиск и страницы KVR; остальные написания KVR отдаёт 403 — не проверены |
| Другие аудио-компании | **Berg Audio — французский дабтехно-лейбл** (Bandcamp, Beatport, SoundCloud, RA). Плагинов не делает, но имя «Berg Audio» в электронной музыке занято. Ещё Berg Sound (лейбл на Discogs), Berg Larsen (мундштуки), Humes & Berg (кейсы) | веб-поиск |
| App Store | «Berg App» — семейный органайзер, не аудио | apps.apple.com |
| Код AU `Berg` | Столкновений нет: на машине 82 AU, `Berg` только у нас; на GitHub `PLUGIN_MANUFACTURER_CODE Berg` — ноль. Общего реестра кодов у Apple больше нет, так что это проверка, а не гарантия | `auval -a`, поиск по GitHub |
| Товарные знаки | BERG у Berg Toys — батуты и картинги, другой класс; BERG ELECTRONICS мёртв с 2005. **Поиск USPTO и EUIPO по классам 9 и 15 не сделан** — нужен браузер | trademarkelite, justia |

**Домены** — whois регистров, 13.09.2026, проверено дважды:

| Домен | Состояние |
|---|---|
| `berg.audio` | **свободен** (`whois.nic.audio`: DOMAIN NOT FOUND); премиальная цена не проверена |
| `bergplugins.com`, `berg-plugins.com`, `bergdsp.com` | **свободны** |
| `bergaudio.net` | свободен — по одной проверке, не повторялась |
| `bergaudio.com` | занят с 2020, сайта нет |
| `berg-audio.com` | занят с 2015, страница «BERG AUDIO» — вероятно, лейбл |
| `berg.fm`, `bergsound.com` | заняты |

**Вывод:** «Berg» без приставок годится. **Не называться «Berg Audio»**: это имя лейбла,
и поиск будет их путать. Домен не куплен — это решение пользователя и деньги, вопрос
в сессию 24. Остаётся открытым поиск знака в USPTO/EUIPO.

### Сессия 24: домен под портфолио

Ответ пользователя вместо «покупаем / нет»: хочется сайт со всем портфолио разработчика —
можно ли для него `berg.audio`? **Можно:** `.audio` — открытая зона без ограничений
на содержание, домен — просто адрес. Схема, которая закрывает оба случая: `berg.audio` —
портфолио, страница плагина — раздел (`berg.audio/midi-delay`), второй плагин — соседний
раздел. Оговорка одна: `.audio` говорит «звук», и если в портфолио будет много не-аудио
работ, адрес будет обещать не то. Домен **не куплен**, цена продления не проверена —
вопрос «покупаем» уходит в сессию 25 уже с этим контекстом.

### Критерии приёмки
- [ ] Имя выбрано, не занято на KVR, домен зарегистрирован — **имя выбрано и на KVR свободно; домен не куплен**
- [ ] Страница открывается, скачивание работает с чистой машины без регистрации
- [ ] Форма подписки собирает адреса и они где-то хранятся
- [ ] FAQ отвечает минимум на: какие хосты, какие ОС, почему не Linux, куда писать о баге
- [ ] На странице указано, что плагин бесплатный, и нет обещаний поддержки, которых не будет

---

## [50] Бесплатный релиз: рассылка, KVR, видео
**Labels:** release
**Milestone:** M5

### Описание
Запуск по плану из [STRATEGY.md](STRATEGY.md) §8. Порядок жёсткий: сначала подписанные
сборки под обе платформы (#33), потом сайт (#49), и только потом рассылка — письмо
о релизе, ведущее на неработающую ссылку или на неподписанный бинарник, тратит
единственный шанс на внимание.

Письмо одно и то же на все сайты: что делает одной фразой, скриншот, видео на 30 секунд,
ссылка, слово «бесплатно». Адресаты: BPB, KVR News, Integraudio, rekkerd.org,
Synth Anatomy, Audio Plugin Guy.

Отдельно: страница продукта на KVR (индексируется и живёт годами) и участие в KVR
Developer Challenge, если попадаем в окно проведения.

Видео — по одному в неделю первый месяц, формат из STRATEGY.md §8: сухой вокал две
секунды, эффект, всё. Материал берётся из #48.

### Критерии приёмки
- [ ] Подписанные установщики под macOS и Windows скачиваются и ставятся с чистой машины
- [ ] Письмо разослано по шести адресатам в один день
- [ ] Страница продукта на KVR создана
- [ ] Минимум четыре коротких видео опубликованы
- [ ] Через месяц записаны числа: скачивания, подписки, откуда пришли

---

## [51] Prelude: хвост из будущего, перевёрнутый
**Labels:** dsp, post-mvp, idea
**Milestone:** Post-MVP

### Описание
Идея пользователя, сессия 14. Дилей играет **до** фразы, а не после: берёт кусок вокала,
который прозвучит через N миллисекунд, переворачивает его и подаёт наплывом ровно к началу
этой фразы. Слушатель слышит подготовку к тому, чего ещё не было. Не только для голоса —
для любого инструмента с внятными фразами.

### Почему это вообще возможно
Заглянуть в будущее плагин может — тем же механизмом, которым уже пользуется режим Follow
(ADR 0006). Плагин просит у хоста скомпенсировать латентность L и придерживает сухой сигнал
ровно на L. С этого момента у него на руках L миллисекунд входа, которых сухой выход ещё
не достиг: в момент, когда наружу идёт вход времени t, кольцо уже содержит вход до t + L.
Это не трюк, а обычная схема просмотра вперёд — так работают лукахед-лимитеры.

### Почему это ложится именно на этот плагин
Обычный реверс-дилей размазывает вслепую: он не знает, где начинается фраза, и наплыв
приходится ставить руками. **Здесь фразу отмечает MIDI.** Нота говорит и когда наплыв
обязан закончиться, и какой высоты он должен быть. То есть наплыв не просто шумит перед
фразой, а **объявляет аккорд, который сейчас прозвучит**, — и объявляет в тональности.
Прецеденты у реверс-реверба и пре-дилея есть; MIDI-расписания и транспонирования у них нет.

### Что для этого уже готово
- `dryDelay` и `alignmentSamples()` — придержать сухой и попросить компенсацию у хоста
- `delayBuffer` — кольцо уже хранит всё, что нужно, и читается по дробной позиции
- Обратное воспроизведение — это чтение кольца со смещением, растущим на 2 за сэмпл.
  Отдельного кода не нужно: тот же `DelayBuffer::read`, тот же интерполятор
- `Voice` — огибающая attack/release уже сгладит края перевёрнутого куска, а питчер
  уже транспонирует то, что ему дали, безразлично к направлению

### Что придётся решить
- **Третье объявленное исключение из нулевой латентности.** Сейчас их два, оба в ADR 0006.
  Здесь латентность равна длине наплыва — сотни миллисекунд, а не 180. Нужен свой ADR
  и проверка PDC в FL Studio на таком масштабе: 180 мс там работают, про 1 с неизвестно.
- **В Standalone режим не работает вовсе, и это надо честно показать в окне.** Будущего
  без хоста нет. То же и для живого мониторинга: это эффект сведения, не исполнения.
- **Два разных эффекта, и их стоит развести.** Наплыв вперёд (кусок будущего играется
  как есть, до фразы) и наплыв перевёрнутый. Второй — классический swell, первый —
  «призрак» фразы. Оба дешевле сделать одним режимом с галкой, чем двумя режимами.
- **Что делать, когда ноты нет.** Без MIDI наплыву не к чему привязаться; вероятный ответ —
  без ноты режим молчит, как молчит весь плагин сейчас.

### Почему не сейчас
Веха M4 — пресеты и интерфейс, M5 — бесплатный релиз ([STRATEGY.md](STRATEGY.md) §9).
Класть новый режим поверх непроверенных пресетов значит переделывать оба.

**Но у идеи есть отдельная стратегическая ценность, и её стоит записать.**
[STRATEGY.md](STRATEGY.md) §3 и §5 упираются в то, что плагин непродемонстрируем:
демо-видео «послушайте, как почти ничего не изменилось» не существует, и #48 заведена
именно поэтому. Наплыв из будущего слышно с первой секунды и без объяснений — это
готовое видео на тридцать секунд. То есть это кандидат либо в заголовок версии 1.1,
либо в платную часть ([STRATEGY.md](STRATEGY.md): деньги со второго продукта).

### Критерии приёмки
- [ ] Наплыв заканчивается ровно на MIDI-ноте, а не «примерно перед ней» (замер)
- [ ] Перевёрнутый кусок — это ровно тот материал, который прозвучит, а не соседний
- [ ] Латентность честно репортится и проверена в FL Studio на длине до 1 с
- [ ] В Standalone режим объявлен неработающим прямо в окне, а не молча делает не то
- [ ] Края наплыва не щёлкают: детектор из раздела «Анти-клик» не ловит выброса
- [ ] Наплыв транспонируется в ноту, то есть объявляет высоту, а не только ритм

---

## [52] Своё лицо в оформлении

**Labels:** ui
**Milestone:** Post-MVP

### Описание
Вердикт сессии 17 по снимкам [#26](#26): функция интерфейса принята целиком
(«функционал дизайна топчик»), внешний слой — нет («слишком обычно», «может придумаем
свою фичу в дизайне»). Тёмный фон с одним акцентом решает задачу читаемости и не решает
задачу узнаваемости: так выглядит любой плагин, вышедший после 2015 года.

Претензия именно к отсутствию своего, а не к палитре: менять `accentColour` на другой
оттенок значит поменять один обычный вид на другой обычный.

### Где искать это лицо
Не в украшениях поверх сетки, а в том единственном, чего у обычного дилея нет, —
**в ленте нот**. Она уже показывает то, чего не показывает никто: какая нота держит
хвост и куда он транспонирован. Сейчас она нарисована как служебное табло. Кандидаты,
от дешёвого к дорогому:

1. Хвост на ленте живёт во времени — след ноты гаснет за свою длину, а не пропадает
   с отпусканием клавиши. Видно ровно то, что слышно.
2. Интервал транспонирования рисуется дугой от корневой ноты к звучащей: ratio 1.335
   в шапке — это число, дуга — это музыка.
3. Типографика и рамка окна как подпись продукта, а не как стиль по умолчанию.

### Почему не сейчас
M4 — интерфейс и пресеты, M5 — бесплатный релиз. Задача косметическая и релиз
не блокирует; браться за неё до [#30](#30) и [#33](#33) значит отложить выход
ради внешнего вида. Но в версию 1.0 она просится: у бесплатного плагина скриншот
работает вместо рекламы ([STRATEGY.md](STRATEGY.md) §3).

### Критерии приёмки
- [ ] Окно узнаётся на скриншоте среди пяти чужих тёмных плагинов
- [ ] Ни одна из правок не ломает правила [#26](#26): мёртвая ручка гаснет вместе
      со своим числом, сменившая смысл меняет подпись
- [ ] Лента остаётся читаемой на масштабе 75 % ([#29](#29))
- [ ] Тексты в окне — только ASCII по-английски

---

## [53] Arp Echo превращается в кашу

**Labels:** dsp, preset
**Milestone:** M5

### Описание
Вердикт сессии 17 по `~/Downloads/BERG-S15/s15-2-arp-echo.wav` (Mix 30): громкость
в порядке, но хвост «превращается в кашу». Разбор — [#48](#48), раздел «Вердикт
по перерендеренному Arp Echo».

Пресет: `division` 7 (1/8. — точка каждые три восьмых), `feedback` 45, `voices` 8,
`attack` 1, `mix` 30. Плотность повторов и глубина петли перемножаются: к четвёртому
повтору на одну долю приходится несколько хвостов, каждый в своей высоте.

### Что проверить прежде, чем крутить числа
Это первая претензия к самому звуку хвоста, а не к его уровню, и «покрутить feedback»
здесь — угадывание. Порядок такой:
1. Замерить плотность: сколько одновременно живых голосов держится на арпеджио
   через 2 с после начала. Снимок голосов из [#27](#27) уже считает это число.
2. Отделить причину от пресета: та же каша на `voices` 4 — значит, дело в петле;
   не та же — значит, в числе голосов.
3. Только потом решать, чем лечить: `feedback` вниз, `voices` вниз, High Cut
   на хвосте ([#22](#22)) или разрежение по образцу Dense Rap ([#48](#48)).

### Критерии приёмки
- [ ] Причина названа замером, а не подобрана на слух вслепую
- [ ] Правка — в пресете, если это пресет; в DSP — только если ломается и на умолчаниях
- [ ] Рендер на том же материале оставлен на следующую сессию, вердикт получен
- [ ] Остальные пять пресетов от правки не поехали

### Сессия 18: вердикт не получен, лечение не начато

`s17-3-arp-echo-mix30.wav` — тот же пресет после снижения Mix до 30. Ответа на вопрос
«с какой секунды и на чём именно слышна каша» нет, вопрос задан второй раз.
Код не тронут намеренно: порядок из раздела выше требует сперва замерить плотность
голосов, а без указания на секунду замер некуда прицелить. Крутить feedback вслепую —
ровно то, что этот раздел запрещает.

### Сессия 19: вопрос «с какой секунды» снят, задача остаётся

Ответа нет в третий раз. **Снят вопрос, но не задача:** претензию «каша» пользователь
высказал сам, в сессии 17, и уточнение было удобством, а не условием. Прицел замера
меняется с секунды на весь рендер: число живых голосов по времени на материале
`s17-3` и та же кривая на `voices` 4. Разойдутся — дело в числе голосов, совпадут —
в петле. Это DSP-сессия; в сессии 19 не начата.

---

## [54] pluginval валит VST3 на восстановлении bool-параметров

**Labels:** test
**Milestone:** M5

### Описание
`pluginval --strictness-level 10` на VST3 падает в тесте «Plugin state restoration»
примерно в трёх прогонах из пяти. Сообщение всегда об одном и том же:

```
!!! Test 3 failed: Tempo Sync not restored on setStateInformation
    -- Expected value within 0.1 of: 1, Actual value: 0.688092
```

Падают **только** `Tempo Sync` и `Ping-Pong` — два не-bypass булевых параметра.
Ни один параметр с непрерывной шкалой не падал ни разу.

### Что установлено в сессии 17

**Это не регрессия сессии 17.** Проверено прямо: правки убраны в `git stash`, VST3
пересобран из `88af2f3` — того самого коммита, на котором сессия 16 записала
«pluginval strictness 10 зелёный», — и падает так же, три прогона из трёх. Запись
сессии 16 неверна: там либо проверялся AU, либо уровень был другой.

**AU проходит на том же уровне 10, тем же бинарником pluginval.** Это и есть главная
улика: состояние плагина восстанавливается верно, разница в обёртке.

**Собственный тест round-trip зелёный** (`test_processor.cpp`, раздел про пресеты
и масштаб окна): состояние сохраняется и читается точно, включая bool.

**Механизм найден в исходниках JUCE.** `VST3Parameter::getValue` возвращает не значение
плагина, а хостовый кэш `cachedParamValues`. Хост пишет в bool-параметр случайное
0,69 — кэш становится 0,69, плагин сворачивает это в `true`. При восстановлении
плагин ставит `true`, значение у него **не меняется**, уведомления нет — и в кэше
остаётся 0,69. Тест сравнивает кэш и падает.

**Две попытки вылечить со стороны плагина не сработали, обе откачены.**

| Попытка | Результат |
|---|---|
| `updateHostDisplay()` после `replaceState` | 3 зелёных, потом 2 красных из 4 |
| `setValueNotifyingHost` по всем параметрам | 2 зелёных из 5 |

Причина, по которой не помогает ни то ни другое: уведомление о смене параметра
маршалится в поток сообщений, а pluginval читает кэш сразу после
`setStateInformation`, не прокрутив очередь. `--validate-in-process` падает так же,
то есть дело не в межпроцессном обмене.

**Вывод: со стороны плагина чинить нечем, и код, который «почти помогает», убран.**
Правка, не делающая проверку зелёной, но добавляющая рассылку всех параметров при
каждой загрузке проекта, — это новый риск в обмен на ничто.

### Чем это грозит пользователю
Ничем слышимым: звук восстанавливается верно. В худшем случае хост секунду показывает
у галки чужое число, пока не прокрутится очередь сообщений. Живьём в FL Studio
такого не наблюдалось ни разу за шестнадцать сессий.

### Критерии приёмки
- [x] Решено, что считать зелёным: расхождение объявлено известным и записано в README
      рядом с командой валидации (сессия 18)
- [x] ~~Если объявлено известным — проверено на стоковом примере JUCE~~ — не понадобилось:
      вылечено в сессии 24, до/после замерено на фиксированных зёрнах pluginval
- [x] AU и собственный round-trip остаются зелёными — перепроверено в сессии 18

### Сессия 18: перемерено и записано в README

Четыре прогона на HEAD: **один красный, три зелёных.** Красный — те же два параметра
и ни одного другого:

```
!!! Test 3 failed: Tempo Sync not restored -- Expected within 0.1 of: 1, Actual: 0.803255
!!! Test 13 failed: Ping-Pong not restored -- Expected within 0.1 of: 0, Actual: 0.479514
```

Мигание подтверждено вторично, механизм тот же. Расхождение объявлено известным
и записано в `README.md` рядом с командой валидации, вместе с оговоркой, что AU
и собственный round-trip на том же состоянии зелёные. Задача **не закрыта**: остаётся
вторая половина — проверить то же на стоковом примере JUCE с bool-параметром, чтобы
«это JUCE, а не мы» стало замером.

**Побочно: pluginval и `auval` открывают окно плагина на экране** и мешают работать,
если запускать их в фоне. У pluginval есть `--skip-gui-tests`; отрисовка при этом
остаётся покрыта офлайн-снимком `ProcessorTest --shot`, который окна не создаёт.
Команда с этим флагом теперь стоит в README и в [DAW_COMPAT.md](DAW_COMPAT.md).
У `auval` такого флага нет.

### Сессия 21: половина задачи ушла вместе с галкой

`Ping-Pong` стал списком `Stereo` ([#55](#55)). Три прогона pluginval с `--skip-gui-tests`:
два зелёных, в третьем — только `Tempo Sync not restored on setStateInformation`, 0,500228
вместо 1. Второй bool этой задачи не вылечен, а исчез; стоковый пример JUCE по-прежнему
не проверен, и задача остаётся открытой на одном `Tempo Sync`.

### Сессия 23: теперь это красит CI

Локально — снова один из трёх (0,836 вместо 1). **В CI на macOS pluginval покраснел
во втором прогоне из двух** (0,711 вместо 1), и падение pluginval роняет весь прогон ([#4](#4)).
Плавающая красная CI приучает не смотреть на красное. Решать надо до релиза: либо
чинить, либо явно пропускать эту проверку в CI с записью здесь — но не молча.

### Сессия 24: вылечено со стороны плагина

**Вывод сессии 17 «со стороны плагина чинить нечем» неверен: механизм был найден не тот.**
Исходник теста (pluginval v1.0.4, `BasicTests.cpp`): `original = getValue()`,
`setValue (random)`, `setStateInformation (original)`, сравнение. Корень не в очереди
сообщений, а в `AudioParameterBool::setValue`: он хранит `value = newValue` как есть,
и `getValue` отдаёт 0,69, а не 1. APVTS в `replaceState` видит, что «включено» совпадает,
и ничего не пишет. Обёртка VST3 в `setComponentState` отдаёт хосту `param->getValue()` —
те же 0,69. Все «Actual» из записей выше (0,688 / 0,803 / 0,500 / 0,836 / 0,711) —
это число, которое тест сам записал; падение — только когда оно легло на ту же сторону.
Отсюда и «мигание»: зерно у pluginval случайное. Что именно рассылали попытки сессии 17,
не записано (код откачен); в 0/1 они значение не сворачивали, иначе проверка бы позеленела.

**Починка:** после `replaceState` каждая галка сворачивается в ровные 0/1 через
`setValue`, без уведомления хоста — по смыслу значение не меняется, и загрузка проекта
не должна выглядеть автоматизацией. Тест в разделе «Состояние» повторяет шаги pluginval
и без починки краснеет.

**Замер, а не удача зерна:** `--random-seed` и `--disabled-tests` со всеми тестами, кроме
этого. До починки зёрна 1, 2, 3, 7, 8 — красные (0,872 / 0,703 / 0,533 / 0,855 / 0,685),
4, 5, 6 — зелёные. После — 8 из 8 зелёные. Полный прогон strictness 10 с `--skip-gui-tests` —
три зелёных из трёх (зёрна 0x2a6c651, 0x17c9e8a, 0x4569878). README, DAW_COMPAT и RELEASE
больше не называют это известным расхождением. Стоковый пример JUCE не нужен: причина
в JUCE доказана исходником и нашим тестом, и обходится она у нас.

---

## [55] Stereo Mode: хор в Follow, ping-pong в Free

**Labels:** dsp, sound, ui
**Milestone:** M5 — до релиза, по плану пользователя

### Описание
Предложение пользователя после сессии 19: у эффекта нужен режим стерео, по умолчанию
«хор», а в остальных режимах по умолчанию ping-pong. Сейчас стерео — два органа:
Width разводит голоса по номеру слота, галка Ping-Pong чередует стороны по нотам,
и по умолчанию ping-pong выключен везде ([#23](#23)).

**Как прочитано — подтвердить одной строкой.** «Хор» — режим Follow: хвост звучит
вместе с сухим, это гармонический слой, и плагин открывается именно в нём (Chord Pad).
«Остальные режимы» — Free, то есть дилей. Другое прочтение, «хор» как пресет
Ghost Choir, меняет только таблицу умолчаний, а не устройство.

### Предлагаемое устройство
Параметр **Stereo** со списком `Auto / Choir / Ping-Pong` вместо галки Ping-Pong.
`Auto` — умолчание: в Follow звучит как Choir, в Free как Ping-Pong. Подпись в окне
меняется по правилу [#26](#26): `Stereo - auto: choir`. Width остаётся размахом
в обоих режимах.

**Почему `Auto`, а не перещёлкивание значения при смене Time Mode.** Параметр, который
переписывает себя при движении другого, ломает автоматизацию и undo хоста:
пользователь выставил Ping-Pong, тронул Time Mode — и выбор пропал. `Auto` исполняет
«умолчание зависит от режима» буквально и явный выбор не трогает.

### Три развилки — решать рендером A/B, а не по аналогии
1. **Что такое «хор».** Сейчас в Follow одна нота — один голос в центре: разлёт
   по слотам на одной ноте не даёт ширины вовсе, и это часть «плоско».
   - а) разлёт по слотам, как сейчас: дёшево, на одной ноте моно;
   - б) каждая нота поётся парой голосов, влево и вправо, с расстройкой ±5–10 центов
     и сдвигом 10–25 мс: широко с первой ноты. Цена — полифония: 4 ноты на 8 голосов.
     Процессор не дорожает, голосов по-прежнему не больше восьми.
2. **Что такое «ping-pong».** Наш — по нотам: классический, по повторам, в этой
   архитектуре не слышен, потому что голос читает моно-сумму кольца ([#23](#23)).
   **Ловушка именно для умолчания в Free: одна удержанная нота уходит в левый борт
   целиком и там остаётся.**
   - а) по нотам, но первая нота — в центр, дальше чередование;
   - б) классический: кольцо L/R с перекрёстной обратной связью и два чтения
     на голос — два питчера. На HQ это вдвое дороже, около 6,4 % ядра при бюджете
     5 % ([#30](#30)).
   Слово «ping-pong» почти наверняка слышится как «повторы прыгают» — а это только (б).
3. **Моносовместимость.** Вердикт сессии 17: моно важнее ширины. Пара по бортам
   с расстройкой и классический ping-pong роняют моно-сумму сильнее нынешнего
   (сейчас Width 100 с ping-pong — −0,69 dB). Новые режимы проходят через тот же замер
   «Моносовместимость» с полом −3,1 dB, числа — в таблицу [#23](#23).

### Что заденет
- **Пресеты.** Sung Vocal и Dense Rap ставят `pingPong 1` — переходят на Ping-Pong;
  Chord Pad и Ghost Choir получают Choir через Auto.
- **Состояние.** Проект со старой галкой открывается в соответствующем значении Stereo:
  миграция на загрузке, `stateVersion` +1. Чужих проектов до релиза нет, но свои есть,
  и сессия 19 показала, как это выглядит в FL, когда о них забыли.
- **Тесты.** «Ping-pong по нотам», «Моносовместимость», «Фабричные пресеты», список
  параметров в «Анти-клик». Регрессионные рендеры ([#34](#34)) — в Free, и с `Auto`
  стали бы ping-pong: `plainLoop` закрепляет прежний разлёт, эталоны не переписываются.
- **Возможно, половина [#54](#54).** Ping-Pong — один из двух bool, на которых валится
  pluginval; параметры-списки там не падали ни разу. Проверить, а не обещать.

### Ответы пользователя, сессия 21

- **Прочтение подтверждено:** хор — Follow, ping-pong — Free. Ответ дан вместе с вопросом
  о ping-pong: вариант «послушать оба» начинался словами «да, Auto такой».
- **Развилка 2 — «послушать оба»:** по нотам и классический, рендерами A/B.
- Развилка 1 пользователю не задавалась — рендерами A/B по плану сессии.

### Сделано в сессии 21: параметр и прототипы обеих развилок

**Параметр `stereo`** `Auto / Choir / Ping-Pong`, по умолчанию Auto, — на месте галки
в списке параметров: номера соседей не сдвигаются. Правило одно на процессор и окно —
`isChoirStereo()`: Choir, или Auto в Follow. В окне список стоит в полосе Mix; в Auto
подпись говорит, чем звучит сейчас: `Stereo - choir` или `Stereo - ping-pong`.

**Миграция, `stateVersion` 2.** Проект версии 1: `pingPong 1` → Ping-Pong, `pingPong 0` →
**Choir, а не Auto** — проект обязан открыться тем звуком, с которым сохранён, а без галки
голоса расходились по слотам и во Free тоже. Старый узел из состояния удаляется.

**Пресеты.** Sung Vocal и Dense Rap — Ping-Pong явно, Chord Pad — Auto в Follow, то есть хор.
**Ghost Choir — Choir явно, и здесь описание задачи было неправо:** выше написано, что Ghost
Choir получит хор через Auto, а пресет стоит во Free — Auto сделал бы из хора ping-pong.
**Arp Echo и Octave Drop Stereo не называют и во Free стали ping-pong через Auto** — ровно
по правилу пользователя, но звук пресетов, одобренных в сессии 15, изменился, и на слух
это не проверено.

**Ловушка развилки 2 закрыта в основной ветке (2а):** нота в тишину уходит в центр, дальше
влево-вправо. Одна удержанная нота во Free больше не сидит в левом борту.

**Прототипы — не параметры.** `MidiDelayProcessor::forks`, ключи рендера `pairs=1` и
`classic=1`: хост их не видит, в проект они не пишутся, вердикт удаляет их вместе
с проигравшей веткой кода.
- **Хор парой (1б):** нота двумя голосами по бортам, ±7 центов, правый позже на 15 мс,
  velocity пополам — по мощности как один голос. Цена — полифония, 4 ноты на 8 голосов.
- **Классический ping-pong (2б):** сухой моно-суммой в левый канал кольца, отводы
  крест-накрест, голос читает каналы порознь двумя питчерами. Ввод кольца — рампа 50 мс.
  Вторая пара движков выделена всем голосам всегда.

| Замер | Результат |
|---|---|
| Три ноты по очереди, баланс −1…+1: Choir | 48 −0,10, 60 0,00, 72 +0,10 |
| То же, Ping-Pong по нотам | 48 +0,41, 60 0,00, 72 −0,41 |
| Хор парой, одна нота | 2 голоса, баланс 0,000 |
| Классический, повторы 1 и 2 | −0,41 и +0,41 |
| Моно-сумма на умолчаниях (Width 100, Diffusion 50) | Choir −0,03, по нотам −0,63, парой −0,68, классический −0,48 dB; все строки — в [#23](#23) |
| Смена Stereo и прототипов на хвосте, 30 с | отношение 1,4 при пороге 8 |
| Общий стресс #25, `stereo` в списке | 4,5 / 1,1 / 1,7 на 48 / 44,1 / 96 кГц |
| CPU, `--bench hq hold`, три прогона | 4,4 / 4,4 / 4,4 % — как до правок; классический ping-pong — 6,7 / 6,8 / 6,8 %, выше бюджета 5 % ([#30](#30)) |
| Регрессия Clean | байт-в-байт: `--regress update` не изменил ни одного из четырёх файлов |
| pluginval, три прогона | два зелёных; в третьем — только `Tempo Sync` ([#54](#54)) |
| `auval -v aumf Mdly Berg` | зелёный |

**Рендеры — `~/Downloads/BERG-S21/`**, таблица и вопросы — в `prompts/NEXT.md` сессии 22.

### Вердикт пользователя по BERG-S21, сессия 22

Ответы окном вопросов, дословно:
- **Развилка 1, хор:** «s21-2 пара».
- **Развилка 2, ping-pong:** «По нотам (3, 5)».
- **Релиз или Ghost:** «что считааешь неужным» — решение за сессией.

Пара остаётся и становится Choir, разлёт по слотам уходит. По нотам остаётся Ping-Pong,
классический уходит вместе со второй парой движков. Жалобы на громкость пары не было —
вопрос «громкость или ширина» не задавался.

### Сделано в сессии 22: проигравшее удалено

- **Удалено, а не выключено:** разлёт по слотам (`panForSlot`), классический ping-pong —
  вторая пара движков в `Voice`, третий scratch в пуле, двухпроходный вход кольца,
  `crossSmoothed`; прототипы `forks`, ключи рендера `pairs` и `classic`, `--bench … classic`.
  `Voice.h` и `Voice.cpp` вернулись к сессии 20 целиком. Раскладок осталось две, и enum
  стал флагом `VoiceManager::setChoir`.
- **Самокража пары починена** — это был `ponytail:` прототипа. Свежий голос стоит на нуле
  огибающей и потому самый тихий в пуле: второй голос пары забирал первый. Теперь
  `findVoiceFor` не отдаёт слот первого. При Voices 1 пары нет — нота одним голосом в центре.
  Chord Pad на материале BERG-S21 от починки не изменился ни на байт: `s21-2` совпал.
- **Тесты вне раздела #55 стоят на Ping-Pong** (`plainLoop`, регрессия): нота в тишину там —
  один голос в центре, бит-в-бит нулевой слот разлёта. Эталоны `delay`, `voice`, `feedback`,
  `tape`, `lofi` не изменились ни на байт; `chord` переписан — аккорд в ping-pong расходится
  иначе, чем по слотам, уровень тот же (−25,3 и −25,4 dBFS).
- **Старые проекты с `pingPong 0`** открываются в Choir, как и решено в сессии 21, но звучат
  теперь парой: разлёта, в котором они сохранены, больше нет. Чужих проектов до релиза нет.
- **Ghost Choir изменился и не слушан.** Он стоит на Choir явно, и разлёт стал парой.
  A/B — в `~/Downloads/BERG-S22/`, вопрос — в `prompts/NEXT.md` сессии 23.

### Вердикт сессии 23 по BERG-S22

Дословно: **«s22-1 пара»**. Ghost Choir остаётся на Choir, звучит парой. Код не менялся.

| Замер | Результат |
|---|---|
| Хор, одна нота | 2 голоса, баланс 0,000 |
| Хор на полном пуле | Voices 2: новая нота на двух голосах; Voices 1: на одном |
| Ping-Pong по нотам, три ноты | 48 +0,41, 60 0,00, 72 −0,41 — как в сессии 21 |
| Моно-сумма | таблица в [#23](#23), сессия 22 |
| Смена Stereo на хвосте, 30 с | отношение 1,3 при пороге 8 |
| CPU, `--bench hq hold`, три прогона | 4,5 / 4,6 / 4,5 % |
| pluginval, три прогона | два зелёных; в третьем — только `Tempo Sync` ([#54](#54)) |
| `auval -v aumf Mdly Berg` | зелёный |

### Критерии приёмки
- [x] Прочтение «хор — Follow, ping-pong — Free» подтверждено пользователем
- [x] Развилки 1 и 2 решены по рендерам, вердикт записан здесь
- [x] Смена Stereo на звучащем хвосте не щёлкает — детектор из «Анти-клик»
- [x] Моно-сумма каждого режима замерена, на значениях по умолчанию не ниже −3,1 dB
- [x] Старый проект с `pingPong 1` открывается в Ping-Pong
- [x] Регрессионные эталоны не переписаны — Clean байт-в-байт; `tape` и `lofi` добавлены по [#56](#56)

---

## [56] Характер звука: Tape, Lo-Fi и регулятор Age

**Labels:** dsp, sound
**Milestone:** M5 — до релиза, по плану пользователя

### Описание
Вердикт пользователя после сессии 19: рядом с Valhalla Delay звук «слишком плоско,
пластиково», не хватает обработок «типа лоу-фай и гоуст, сатурации и всё такое».

**Это пересмотр решения сессии 11, и он законен.** Тогда режимы Valhalla решили
не заводить: «пресеты поверх тех же ингредиентов» — диффузии, фильтров, модуляции,
ducking ([ROADMAP](ROADMAP.md), M3). Ингредиенты сделаны ([#44](#44)–[#47](#47)),
а ухо говорит «пластиково». Вердикт уха главнее прежнего рассуждения.

### Почему пластиково — по коду, а не по догадке
Всё, что красит хвост, кроме фильтров, стоит **только на отводе обратной связи**
(`renderSegment`): диффузия, модуляция времени, ограничитель. Первый хвост проходит
лишь однополюсные фильтры на входе кольца. Отсюда:

1. **На feedback 0 плагин — чистая транспонированная копия.** Это Chord Pad, в котором
   плагин открывается, и Dense Rap. Три «ингредиента Valhalla» до них не доходят вовсе.
2. **Насыщения фактически нет.** Колено ограничителя 0,7, обычный круг — около 0,33.
   Сессия 15 так и записала: «на слух не оценивалось, на рендерах не включается» ([#44](#44)).
3. **Модуляция периодическая** — сумма двух синусов. У ленточных режимов Valhalla она
   случайная.

Плюс гипотеза, которую проверит только рендер: гладкий призвук фазового вокодера HQ.
Ленточная неровность его маскирует.

### Что известно про Valhalla
Исследование сессии 19. valhalladsp.com закрыт от автоматического чтения, поэтому факты —
из поисковых выдержек постов Valhalla и со страницы KVR; первоисточники в конце раздела.

- **Характер — это режим, Era и Age.** Режим выбирает модель (Tape, HiFi, BBD, Digital,
  LoFi, Ghost, Pitch и другие), Era — вариант внутри модели, Age — износ: шум ленты
  у Tape, битность у Digital (50 % — 12 бит), шум через компандер у BBD.
- **Модуляция у Tape, HiFi и LoFi случайная**; у Tape скорость и глубина зависят
  от времени задержки, у LoFi она хаотическая и очень глубокая.
- **Стерео у Valhalla — отдельная ось**, Style: Single, Dual, Ratio, PingPong, Quad.
  Довод за устройство [#55](#55): Stereo отдельно от Character.
- Drive — «от тёплого до кричащих повторов».

Первоисточники: valhalladsp.com/2019/04/16/valhalladelay-the-mode-control/,
…/valhalladelay-the-controls/, …/valhalladelay-the-style-control/,
valhalladsp.com/2020/11/23/valhalladelay-1-8-2-update-lofi-mode/,
kvraudio.com/product/valhalladelay-by-valhalla-dsp.

### Предлагаемое устройство — минимум, который проверяется ухом
Два параметра, а не десять ручек: пятнадцать почти одинаковых и так не объясняют себя ([#26](#26)).

- **Character:** `Clean / Tape / Lo-Fi`. Clean — нынешний звук бит-в-бит.
- **Age:** 0–100, глубина характера. Одна ручка на всё, как у Valhalla.

| | Tape | Lo-Fi |
|---|---|---|
| Насыщение | мягкое, с пре- и деэмфазисом, растёт с Age | жёсткое, как у дешёвого АЦП |
| Полоса | темнеет с каждым кругом | узкая, около 200 Гц – 4 кГц |
| Модуляция | случайный wow и flutter | глубокий хаотический wow |
| Разрядность и частота | — | от 16 до 6 бит по Age, понижение частоты с алиасингом |
| Шум | шипение по огибающей сигнала | шум по огибающей сигнала |

**Место — вход кольца, рядом с фильтрами, а не один лишь отвод обратной связи.** Тогда
первый хвост окрашен один раз, каждый следующий сильнее — как у ленты, — и характер
слышен на feedback 0. Считается один раз на канал, а не на голос: цена не зависит
от числа голосов. Сухой выход не окрашивается — он идёт мимо кольца.

### Развилки — решать рендером
1. **Wow на чтении голоса.** Решение [#46](#46) — модулировать только петлю, потому что
   дрожание на входе питчера становится уходом высоты. Для Clean оно верно и остаётся.
   Для Tape уход высоты и есть характер, но HQ может сделать из него фальшь, а не ленту.
   A/B: wow только в петле против wow и на чтении голоса.
2. **Сглаживание насыщения.** Нелинейность на 48 кГц без передискретизации даёт алиасинг —
   ту самую цифровую жёсткость, от которой уходим. Для Tape — антипроизводная первого
   порядка (ADAA), это дёшево; для Lo-Fi алиасинг — цель.
3. **Какие пресеты получают характер.** Рендеры пресетов в разных характерах, решает
   пользователь. Кандидат — лёгкий Tape уже в Chord Pad: иначе «пластиково» остаётся
   в первом, что человек услышит.
4. **BBD** — третий характер (компандер, тёмная полоса, шум) — только если Tape и Lo-Fi
   «пластиково» не закроют. Сначала два самых непохожих.

### Ловушки, известные заранее
- **Шум в петле копится.** Шум с входа кольца при feedback 95 % растёт по мощности как
  `1 / (1 − 0,95²)` — втрое по амплитуде. Шум только по огибающей сигнала и с потолком;
  замер уровня в тишине после хвоста.
- **Смена Character на звучащем хвосте.** Кроссфейд двух обработанных версий — сигнал
  сильно коррелированный: equal-power дал бы горб ([ADR 0003](adr/0003-bypass-crossfade.md)),
  линейный запрещён инвариантом. Обход — схема дома: Age старого характера плавно в ноль,
  смена, Age нового из нуля. Кроссфейд не нужен, ADR не нужен.
- **Регрессия.** Clean обязан остаться бит-в-бит: `plainLoop` закрепляет Clean, эталоны
  [#34](#34) не переписываются. Эталоны Tape и Lo-Fi заводятся после вердикта, не раньше.
- **Процессор.** Бюджет — 5 % ядра на HQ ([#30](#30)), восемь голосов занимают 3,2–4,3 %.
  Характер на канал, не на голос, обязан уложиться; замер `--bench`.

### Сделано в сессии 20: прототип на слух

Параметры `character` (Clean / Tape / Lo-Fi, по умолчанию Clean) и `age` (0–100,
по умолчанию 30) — в конце списка параметров, чтобы хосты, помнящие параметры
по номеру, не съехали. В окне — третий ряд полосы Delay; Age гаснет в Clean. Окно
выросло на этот ряд: 672 × 854 вместо 672 × 766. DSP — `Source/DSP/Character.h`,
без JUCE, как диффузор. Пресеты не тронуты: характер в них — после вердикта.

**Место — последним перед кольцом, после фильтров петли**, на канал, а не на голос.
Wow — в той же позиции чтения петли, что дрейф [#46](#46). Развилка 1 (wow на чтении
голоса) не делалась: в восемь рендеров она не помещалась, а без вердикта по самим
характерам сравнивать её не с чем.

| | Tape | Lo-Fi |
|---|---|---|
| Порядок | эмфазис → насыщение → деэмфазис → шипение → темнота | срез низа → клип → шум → выборка-хранение → разрядность → срез верха |
| Насыщение | кубическое мягкое с ADAA первого порядка; эмфазис +6 dB выше 1,5 кГц и точный обратный фильтр после; порог с уровня 4 на Age 0 до 0,33 на Age 100 | жёсткий клип без сглаживания, порог с 1 до 0,25 |
| Полоса | однополюсник 16 → 4 кГц по Age: на Age 30 — 10,6 кГц, на 70 — 6,1 кГц | однополюсники 200 Гц и 4 кГц, от Age не зависят |
| Разрядность и частота | — | 16 → 6 бит и 48 → 2 кГц; на Age 50 — 11 бит и 9,8 кГц |
| Шум | 2 % огибающей на Age 100, потолок −40 dBFS | 4 % огибающей, тот же потолок |
| Wow в петле | случайный: 1,5 мс около 1 Гц и 0,08 мс около 8 Гц | 3,5 мс и 0,3 мс |

Все числа стартовые, их двигает ухо.

**Схема дома, без исключений.** Обе обработки крутятся всегда, даже в Clean,
и подмешиваются множителем: `x + blend · (окрашенный − x)`, blend на полную к Age 10.
Смена характера — глубина старого рампой 50 мс в ноль, подмена ровно на нуле, глубина
нового из нуля (`activeCharacter` против `blockCharacter` в процессоре). Любой характер
на Age 0 равен Clean бит-в-бит — проверено равенством выходов, на этом подмена
через ноль и стоит.

**Округление в петле залипает, поэтому усечение.** Квантователь с округлением при
feedback 95 % оставляет любое значение до десяти шагов самим собой (0,95 · 10 = 9,5 → 10),
и хвост Lo-Fi не кончался бы никогда. Усечённый модуль не больше входа, петля гаснет
до нуля: в замере ниже Lo-Fi через 44 с тишины даёт ровно ноль.

| Критерий | Замер |
|---|---|
| Clean бит-в-бит | регрессия без `update`; запасы до допуска 57 / 43 / 50 / 43 dB — до цифры те же, что у бинарника до правок |
| Слышно на feedback 0: THD+N хвоста, синус 0,5 | Clean −130 dB, Tape 30 −32,5, Tape 70 −18,1, Lo-Fi 50 −34,5 |
| Feedback 95 %, Age 100, петля без фильтров, вход 0,9: пик окна 100 мс | Clean 0,99, Tape 0,20, Lo-Fi 0,21 при потолке 1,9 |
| То же, уровень через 44 с тишины | Clean −104 dBFS, Tape −119, Lo-Fi ровно ноль |
| Смена Character и рывки Age на звучащем хвосте | отношение 2,7 при пороге 8 |
| Общий стресс #25 с character и age в списке | 3,4 / 1,1 / 1,7 на 48 / 44,1 / 96 кГц |
| CPU, `--bench hq hold`, три прогона вперемежку с бинарником до правок | до 4,4 / 4,4 / 4,4 %, после 4,5 / 4,4 / 4,4 % |
| Проект без `character` и `age` | открывается в Clean с Age 30, остальное на месте |

**На горячем входе Tape и Lo-Fi тише Clean** — на 95 % пик впятеро ниже. Это насыщение
и полоса делают обещанное, но на слух громкость читается раньше тембра. У рендеров
сессии уровень файлов расходится не больше чем на 1,2 dB: там сухой в миксе.

**Рендеры — `~/Downloads/BERG-S20/`**: Chord Pad и Sung Vocal × Clean / Tape 30 /
Tape 70 / Lo-Fi 50, таблица и команда — в `prompts/NEXT.md` сессии 21. Яркость против
Clean (RMS разности соседних отсчётов к RMS): Chord Pad темнее на 1,4 / 2,2 / 2,3 dB,
Sung Vocal — на 0,3 / 0,5 / 0,5 dB, у него Mix 40 и сухого больше. Поотсчётная разность
с Clean для HQ в меру не годится: фазовый вокодер на чуть другом входе расставляет фазы
иначе, и разность выходит в −3…−8 dB, что бы ни было слышно.

### Вердикт по рендерам сессии 20 (сессия 21)

Спрошено в начале сессии 21 окном вопросов: стартовое сообщение второй раз пришло
с пустыми ответами. Ответ — выбор из четырёх файлов; «что не так» не написано ни к одному.

| Материал | Лучший | Что не так |
|---|---|---|
| Chord Pad, `s20-1..4` | **clean** | — |
| Sung Vocal, `s20-5..8` | **tape30** | — |

Что из этого следует, и ничего сверх этого:
- **Chord Pad остаётся Clean.** Кандидат развилки 3 — «лёгкий Tape уже в Chord Pad» — ухом отклонён.
- **Sung Vocal получает `{ "character", 1 }, { "age", 30 }`** — ровно то, что звучало в `s20-6`.
- **Константы `Character.h` не двигаются.** Претензий к тембру нет, а двигать по замеру нельзя.
- **Lo-Fi не выбран нигде, но и не отвергнут словами** — остаётся характером без пресета.
- **Развилки 1 (wow на чтении голоса) и 4 (BBD) не открываются:** «ни один» не прозвучало.

**Сделано по вердикту в той же сессии.** Sung Vocal получил Tape 30 — это проверяет тест
«Фабричные пресеты». Эталоны регрессии заведены: `tape` — петля 60 %, Age 30, как `feedback`;
`lofi` — **один проход**, Age 50. Lo-Fi в петле под x86_64 разошёлся на −50 dB к 2,1 с при
допуске −60: квантователь превращает разницу FMA ниже младшего бита в целый шаг, и круг
за кругом она растёт. Один проход держит — запас 43 dB на обеих архитектурах, у Tape 43 и 42.
Петлю Lo-Fi по-прежнему держит тест «Характер»: хвост гаснет до нуля. Clean байт-в-байт:
`--regress update` не изменил ни одного из четырёх прежних файлов.

### Критерии приёмки
- [x] При Character Clean выход бит-в-бит прежний, регрессия зелёная без `update`
- [~] Характер слышен на feedback 0 — замер THD+N да; рендер Chord Pad оставлен,
      слышно ли ухом — вердикт сессии 21
- [x] При feedback 95 % в Tape и Lo-Fi уровень не разгоняется, шум в тишине ограничен
- [x] Смена Character и движение Age на звучащем хвосте не щёлкают
- [x] Ноль аллокаций в `processBlock`, нагрузка в бюджете
- [x] Вердикт уха записан: какие характеры остаются и какие пресеты их получают
- [x] Тексты в окне — только ASCII по-английски

---

## [57] Ghost: частотный сдвиг — в петле или на выходе

**Labels:** dsp, sound, adr
**Milestone:** Post-MVP, 1.1 — решено в сессии 22

### Решение сессии 22: после релиза
На вопрос «Ghost до релиза или в 1.1» пользователь ответил «что считаешь нужным».
Решено — в 1.1, и вот почему. Жалобу «плоско, пластиково» закрывали две вещи, которые
доходят до первого хвоста: характер ([#56](#56)) и стерео ([#55](#55)), и обе сделаны
по вердикту уха. Ghost — не ответ на ту жалобу, а новый режим. Честный Ghost (вариант 2)
спорит с [VISION](VISION.md) §1 и требует ADR, а три варианта A/B — это две-три сессии.
Релиз тем временем держит не звук: подпись, лицензии, имя и CI, не запускавшаяся
с сессии 05. Бесплатный релиз к тому же скажет, нужен ли Ghost кому-то, кроме нас.

### Описание
Вторая половина запроса «лоу-фай и гоуст». Ghost у Valhalla, по выдержкам их постов:
ленточная модель HiFi, **частотный сдвигатель** — сдвиг в герцах и отдельная расстройка
L/R — и диффузия, у которой верх получает меньше фазовой задержки. Era ведёт от «ghostly
voices» до «bouncing ball». Стоит ли сдвигатель у Valhalla в петле — не проверено.

### Почему отдельная задача
Частотный сдвиг **в петле** — это каждый повтор, уехавший дальше предыдущего: спираль.
Прямое нарушение инварианта «feedback берётся до питч-стадии», и не случайное, а по замыслу.
И спор с сутью продукта: высоту хвоста задаёт MIDI ([VISION](VISION.md) §1), а спираль
уводит хвост от нарисованной ноты тем дальше, чем дольше он живёт.

### Варианты
1. **Сдвиг на выходе, без петли.** Инвариант цел. Малый сдвиг в единицы герц
   с расстройкой L/R даёт негармоничное мерцание и ширину, но спирали нет.
   Цена — сдвигатель (Гильберт и SSB) на wet-шину или на голос.
2. **Сдвиг в петле — настоящий Ghost.** Третье объявленное исключение из инварианта,
   ADR до кода — как у Follow ([ADR 0006](adr/0006-follow-mode.md)).
3. **Свой призрак вместо чужого.** [#51](#51) Prelude — наплыв из будущего, перевёрнутый
   и транспонированный в ноту, «призрак фразы», которого у Valhalla нет: его расписывает
   MIDI. Не замена сдвигателю, но кандидат на то же место в меню.

**Имя.** В пресетах уже есть Ghost Choir, характер Ghost рядом с ним будет путать.
Решается вместе с вариантом.

### Критерии приёмки
- [ ] Вариант выбран по рендерам A/B, вердикт записан
- [ ] Если вариант 2 — ADR с объявленным исключением раньше кода
- [ ] При feedback 95 % спираль не разгоняет уровень
- [ ] Без Ghost выход бит-в-бит прежний

